<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tool;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            // Network Tools
            [
                'name' => 'What Is My IP',
                'slug' => 'what-is-my-ip',
                'category' => 'network',
                'controller' => 'Tools\Network\WhatIsMyIpController',
                'route_name' => 'tools.what-is-my-ip',
                'url' => '/tools/what-is-my-ip',
                'meta_title' => 'What Is My IP Address? - Check Your Public IP | Optimizo',
                'meta_description' => 'Find your public IP address instantly. Check your IPv4 and IPv6 address, location, ISP, and network information for free.',
                'meta_keywords' => 'what is my ip, check ip address, find my ip, public ip, ipv4, ipv6',
                'priority' => 0.9,
                'change_frequency' => 'daily',
                'order' => 1,
            ],
            [
                'name' => 'What Is My ISP',
                'slug' => 'what-is-my-isp',
                'category' => 'network',
                'controller' => 'Tools\Network\WhatIsMyIspController',
                'route_name' => 'tools.what-is-my-isp',
                'url' => '/tools/what-is-my-isp',
                'meta_title' => 'What Is My ISP? - Check Your Internet Service Provider | Optimizo',
                'meta_description' => 'Find your Internet Service Provider (ISP) instantly. Check your ISP name, ASN, organization, and network details for free.',
                'meta_keywords' => 'what is my isp, check isp, internet service provider, asn, network provider',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 2,
            ],
            [
                'name' => 'Domain to IP',
                'slug' => 'domain-to-ip',
                'category' => 'network',
                'controller' => 'Tools\Network\DomainToIpController',
                'route_name' => 'tools.domain-to-ip',
                'url' => '/tools/domain-to-ip',
                'meta_title' => 'Domain to IP Converter - Find IP Address of Any Domain | Optimizo',
                'meta_description' => 'Convert domain names to IP addresses instantly. Find the IP address of any website or domain for free.',
                'meta_keywords' => 'domain to ip, dns lookup, find ip address, domain ip converter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 3,
            ],

            // Utility Tools
            [
                'name' => 'Internet Speed Test',
                'slug' => 'internet-speed-test',
                'category' => 'utility',
                'controller' => 'Tools\Utility\InternetSpeedTestController',
                'route_name' => 'tools.internet-speed-test',
                'url' => '/tools/internet-speed-test',
                'meta_title' => 'Free Internet Speed Test - Check Your Connection Speed | Optimizo',
                'meta_description' => 'Test your internet speed for free. Check download speed, upload speed, ping, and jitter instantly.',
                'meta_keywords' => 'internet speed test, speed test, bandwidth test, connection speed',
                'priority' => 0.9,
                'change_frequency' => 'daily',
                'order' => 4,
            ],
            [
                'name' => 'Image Compressor',
                'slug' => 'image-compressor',
                'category' => 'utility',
                'controller' => 'Tools\Utility\ImageCompressorController',
                'route_name' => 'tools.image-compressor',
                'url' => '/tools/image-compressor',
                'meta_title' => 'Free Image Compressor - Compress Images Online | Optimizo',
                'meta_description' => 'Compress JPG, PNG, and WebP images online for free. Reduce file size while maintaining quality. Fast, secure, and easy to use.',
                'meta_keywords' => 'image compressor, compress images, reduce image size, optimize images',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 5,
            ],
            [
                'name' => 'RGB to HEX Converter',
                'slug' => 'rgb-hex-converter',
                'category' => 'utility',
                'controller' => 'Tools\Utility\RgbHexConverterController',
                'route_name' => 'tools.rgb-hex-converter',
                'url' => '/tools/rgb-hex-converter',
                'meta_title' => 'RGB to HEX Converter - Convert Colors Online | Optimizo',
                'meta_description' => 'Convert RGB to HEX and HEX to RGB color codes instantly. Free online color converter for web designers and developers.',
                'meta_keywords' => 'rgb to hex, hex to rgb, color converter, rgb converter, hex converter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 6,
            ],
            [
                'name' => 'Slug Generator',
                'slug' => 'slug-generator',
                'category' => 'utility',
                'controller' => 'Tools\Utility\SlugGeneratorController',
                'route_name' => 'tools.slug-generator',
                'url' => '/tools/slug-generator',
                'meta_title' => 'Free Slug Generator - Create SEO-Friendly URLs | Optimizo',
                'meta_description' => 'Generate SEO-friendly URL slugs from any text. Create clean, readable URLs for better search engine optimization.',
                'meta_keywords' => 'slug generator, url slug, seo url, permalink generator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 7,
            ],
            [
                'name' => 'MD5 Generator',
                'slug' => 'md5-generator',
                'category' => 'utility',
                'controller' => 'Tools\Utility\Md5GeneratorController',
                'route_name' => 'tools.md5-generator',
                'url' => '/tools/md5-generator',
                'meta_title' => 'Free MD5 Hash Generator - Generate MD5 Online | Optimizo',
                'meta_description' => 'Generate MD5 hash from any text instantly. Free online MD5 generator for checksums and data integrity verification.',
                'meta_keywords' => 'md5 generator, md5 hash, checksum, hash generator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 8,
            ],
            [
                'name' => 'Case Converter',
                'slug' => 'case-converter',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CaseConverterController',
                'route_name' => 'tools.case-converter',
                'url' => '/tools/case-converter',
                'meta_title' => 'Free Case Converter - Convert Text Case Online | Optimizo',
                'meta_description' => 'Convert text to uppercase, lowercase, title case, sentence case, and more. Free online text case converter.',
                'meta_keywords' => 'case converter, text converter, uppercase, lowercase, title case',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 9,
            ],
            [
                'name' => 'Username Checker',
                'slug' => 'username-checker',
                'category' => 'utility',
                'controller' => 'Tools\Utility\UsernameCheckerController',
                'route_name' => 'tools.username-checker',
                'url' => '/tools/username-checker',
                'meta_title' => 'Username Availability Checker - Check Username Across Platforms | Optimizo',
                'meta_description' => 'Check username availability across multiple social media platforms instantly. Find available usernames for your brand.',
                'meta_keywords' => 'username checker, check username, username availability, social media username',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 10,
            ],
            [
                'name' => 'Password Generator',
                'slug' => 'password-generator',
                'category' => 'utility',
                'controller' => 'Tools\Utility\PasswordGeneratorController',
                'route_name' => 'tools.password-generator',
                'url' => '/tools/password-generator',
                'meta_title' => 'Free Password Generator - Create Strong Passwords | Optimizo',
                'meta_description' => 'Generate strong, secure passwords instantly. Customize length, characters, and complexity for maximum security.',
                'meta_keywords' => 'password generator, strong password, secure password, random password',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 11,
            ],
            [
                'name' => 'JSON Formatter',
                'slug' => 'json-formatter',
                'category' => 'utility',
                'controller' => 'Tools\Utility\JsonFormatterController',
                'route_name' => 'tools.json-formatter',
                'url' => '/tools/json-formatter',
                'meta_title' => 'Free JSON Formatter - Beautify & Validate JSON Online | Optimizo',
                'meta_description' => 'Format, beautify, and validate JSON data online. Free JSON formatter with syntax highlighting and error detection.',
                'meta_keywords' => 'json formatter, json beautifier, json validator, format json',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 12,
            ],
            [
                'name' => 'Base64 Encoder/Decoder',
                'slug' => 'base64',
                'category' => 'utility',
                'controller' => 'Tools\Utility\Base64Controller',
                'route_name' => 'tools.base64',
                'url' => '/tools/base64',
                'meta_title' => 'Free Base64 Encoder & Decoder - Encode & Decode Base64 Online | Optimizo',
                'meta_description' => 'Free online Base64 encoder and decoder. Encode text to Base64 or decode Base64 to text instantly. Perfect for developers and API testing.',
                'meta_keywords' => 'base64 encoder, base64 decoder, encode base64, decode base64',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 13,
            ],
            [
                'name' => 'QR Code Generator',
                'slug' => 'qr-generator',
                'category' => 'utility',
                'controller' => 'Tools\Utility\QrGeneratorController',
                'route_name' => 'tools.qr-generator',
                'url' => '/tools/qr-generator',
                'meta_title' => 'Free QR Code Generator - Create QR Codes Online | Optimizo',
                'meta_description' => 'Generate QR codes for URLs, text, and more. Free online QR code generator with multiple sizes and instant download.',
                'meta_keywords' => 'qr code generator, create qr code, qr generator, free qr code',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 14,
            ],
            [
                'name' => 'HTML Viewer',
                'slug' => 'html-viewer',
                'category' => 'utility',
                'controller' => 'Tools\Utility\HtmlViewerController',
                'route_name' => 'tools.html-viewer',
                'url' => '/tools/html-viewer',
                'meta_title' => 'Free HTML Viewer - Preview HTML Code Online | Optimizo',
                'meta_description' => 'View and preview HTML code in real-time. Free online HTML viewer with live preview and syntax highlighting.',
                'meta_keywords' => 'html viewer, html preview, view html, html code viewer',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 15,
            ],
            [
                'name' => 'JSON Parser',
                'slug' => 'json-parser',
                'category' => 'utility',
                'controller' => 'Tools\Utility\JsonParserController',
                'route_name' => 'tools.json-parser',
                'url' => '/tools/json-parser',
                'meta_title' => 'Free JSON Parser - Parse & Validate JSON Online | Optimizo',
                'meta_description' => 'Parse and validate JSON data online. Free JSON parser with tree view, syntax validation, and error detection.',
                'meta_keywords' => 'json parser, parse json, validate json, json validator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 16,
            ],

            // YouTube Tools
            [
                'name' => 'YouTube Monetization Checker',
                'slug' => 'youtube-monetization-checker',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\MonetizationCheckerController',
                'route_name' => 'tools.youtube-monetization-checker',
                'url' => '/tools/youtube-monetization-checker',
                'meta_title' => 'YouTube Monetization Checker - Check Channel Eligibility | Optimizo',
                'meta_description' => 'Check if a YouTube channel is monetized. Verify monetization status, subscriber count, and eligibility instantly.',
                'meta_keywords' => 'youtube monetization checker, check monetization, youtube eligibility',
                'priority' => 0.9,
                'change_frequency' => 'daily',
                'order' => 17,
            ],
            [
                'name' => 'YouTube Thumbnail Downloader',
                'slug' => 'youtube-thumbnail',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\ThumbnailDownloaderController',
                'route_name' => 'tools.youtube-thumbnail',
                'url' => '/tools/youtube-thumbnail',
                'meta_title' => 'YouTube Thumbnail Downloader - Download HD Thumbnails | Optimizo',
                'meta_description' => 'Download YouTube video thumbnails in HD quality. Get thumbnails in all sizes (SD, HD, Full HD, Max Res) for free.',
                'meta_keywords' => 'youtube thumbnail downloader, download thumbnail, youtube thumbnail',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 18,
            ],
            [
                'name' => 'YouTube Video Data Extractor',
                'slug' => 'youtube-extractor',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\VideoDataExtractorController',
                'route_name' => 'tools.youtube-extractor',
                'url' => '/tools/youtube-extractor',
                'meta_title' => 'YouTube Video Data Extractor - Extract Video Information | Optimizo',
                'meta_description' => 'Extract YouTube video data including title, description, tags, views, likes, and more. Free video data extractor.',
                'meta_keywords' => 'youtube data extractor, video data, youtube info, extract video data',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 19,
            ],
            [
                'name' => 'YouTube Tags Generator',
                'slug' => 'youtube-tags',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\TagsGeneratorController',
                'route_name' => 'tools.youtube-tags',
                'url' => '/tools/youtube-tags',
                'meta_title' => 'YouTube Tags Generator - Generate Video Tags for SEO | Optimizo',
                'meta_description' => 'Generate optimized YouTube tags for better video SEO. Extract tags from competitors and boost your video visibility.',
                'meta_keywords' => 'youtube tags generator, video tags, youtube seo, generate tags',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 20,
            ],
            [
                'name' => 'YouTube Channel Data Extractor',
                'slug' => 'youtube-channel',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\ChannelDataExtractorController',
                'route_name' => 'youtube.channel',
                'url' => '/tools/youtube-channel',
                'meta_title' => 'YouTube Channel Data Extractor - Extract Channel Information | Optimizo',
                'meta_description' => 'Extract YouTube channel data including subscribers, views, videos, and more. Free channel data extractor.',
                'meta_keywords' => 'youtube channel extractor, channel data, youtube stats, extract channel info',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 21,
            ],
            [
                'name' => 'YouTube Handle Checker',
                'slug' => 'youtube-handle-checker',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\HandleCheckerController',
                'route_name' => 'tools.youtube-handle-checker',
                'url' => '/tools/youtube-handle-checker',
                'meta_title' => 'YouTube Handle Availability Checker - Check @Username | Optimizo',
                'meta_description' => 'Check if your desired YouTube handle (@username) is available. Instantly verify YouTube username availability for your channel.',
                'meta_keywords' => 'youtube handle checker, check handle, youtube username, handle availability',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 22,
            ],

            // SEO Tools
            [
                'name' => 'Meta Tag Analyzer',
                'slug' => 'meta-analyzer',
                'category' => 'seo',
                'controller' => 'Tools\SEO\MetaAnalyzerController',
                'route_name' => 'tools.meta-analyzer',
                'url' => '/tools/meta-analyzer',
                'meta_title' => 'Free Meta Tag Analyzer - Analyze Meta Tags for SEO | Optimizo',
                'meta_description' => 'Analyze meta tags for SEO optimization. Check title tags, meta descriptions, Open Graph, and Twitter Cards instantly.',
                'meta_keywords' => 'meta tag analyzer, seo analyzer, meta tags, analyze meta tags',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 23,
            ],
            [
                'name' => 'Keyword Density Checker',
                'slug' => 'keyword-density',
                'category' => 'seo',
                'controller' => 'Tools\SEO\KeywordDensityController',
                'route_name' => 'seo.keyword-density',
                'url' => '/tools/keyword-density',
                'meta_title' => 'Free Keyword Density Checker - Analyze Keyword Frequency for SEO | Optimizo',
                'meta_description' => 'Free keyword density checker. Analyze keyword frequency and density in your content for better SEO optimization.',
                'meta_keywords' => 'keyword density checker, keyword frequency, seo keyword analysis',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 24,
            ],
            [
                'name' => 'Word Counter',
                'slug' => 'word-counter',
                'category' => 'seo',
                'controller' => 'Tools\SEO\WordCounterController',
                'route_name' => 'tools.word-counter',
                'url' => '/tools/word-counter',
                'meta_title' => 'Free Word Counter - Count Words, Characters & Reading Time | Optimizo',
                'meta_description' => 'Free online word counter tool. Count words, characters, sentences, paragraphs, and estimate reading time instantly.',
                'meta_keywords' => 'word counter, character counter, count words, reading time',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 25,
            ],
            [
                'name' => 'Redirect & HTTP Status Checker',
                'slug' => 'redirect-checker',
                'category' => 'seo',
                'controller' => 'Tools\Network\RedirectCheckerController',
                'route_name' => 'network.redirect-checker',
                'url' => '/tools/redirect-checker',
                'meta_title' => 'Redirect Checker & HTTP Status Code Tool - Free Online',
                'meta_description' => 'Free redirect checker tool to analyze HTTP status codes, trace redirect chains, detect 301/302 redirects, find broken redirects and redirect loops. Essential for SEO and website debugging.',
                'meta_keywords' => 'redirect checker, http status code, 301 redirect, 302 redirect, redirect loop, broken links, seo tool',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 26,
            ],

            // New Utility Tools
            [
                'name' => 'Code Formatter',
                'slug' => 'code-formatter',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CodeFormatterController',
                'route_name' => 'tools.code-formatter',
                'url' => '/tools/code-formatter',
                'meta_title' => 'Free Code Formatter - Format & Beautify Code Online | Optimizo',
                'meta_description' => 'Format and beautify code in multiple languages. Support for HTML, CSS, JavaScript, PHP, Python, Java, C++, and JSON. Free online code formatter.',
                'meta_keywords' => 'code formatter, beautify code, format code, code beautifier, minify code',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 27,
            ],
            [
                'name' => 'CSS Minifier',
                'slug' => 'css-minifier',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CssMinifierController',
                'route_name' => 'tools.css-minifier',
                'url' => '/tools/css-minifier',
                'meta_title' => 'Free CSS Minifier - Minify & Beautify CSS Online | Optimizo',
                'meta_description' => 'Minify CSS to reduce file size or beautify CSS for better readability. Free online CSS minifier and formatter tool.',
                'meta_keywords' => 'css minifier, minify css, css compressor, beautify css, css formatter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 27,
            ],
            [
                'name' => 'JavaScript Minifier',
                'slug' => 'js-minifier',
                'category' => 'utility',
                'controller' => 'Tools\Utility\JsMinifierController',
                'route_name' => 'tools.js-minifier',
                'url' => '/tools/js-minifier',
                'meta_title' => 'Free JavaScript Minifier - Minify & Beautify JS Online | Optimizo',
                'meta_description' => 'Minify JavaScript to reduce file size or beautify JS for better readability. Free online JavaScript minifier and formatter tool.',
                'meta_keywords' => 'javascript minifier, minify js, js compressor, beautify javascript, js formatter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 28,
            ],
            [
                'name' => 'HTML Minifier',
                'slug' => 'html-minifier',
                'category' => 'utility',
                'controller' => 'Tools\Utility\HtmlMinifierController',
                'route_name' => 'tools.html-minifier',
                'url' => '/tools/html-minifier',
                'meta_title' => 'Free HTML Minifier - Minify & Beautify HTML Online | Optimizo',
                'meta_description' => 'Minify HTML to reduce file size or beautify HTML for better readability. Free online HTML minifier and formatter tool.',
                'meta_keywords' => 'html minifier, minify html, html compressor, beautify html, html formatter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 29,
            ],

            // New YouTube Tools
            [
                'name' => 'YouTube Video Tags Extractor',
                'slug' => 'youtube-video-tags-extractor',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\VideoTagsExtractorController',
                'route_name' => 'youtube.video-tags',
                'url' => '/tools/youtube-video-tags-extractor',
                'meta_title' => 'Free YouTube Video Tags Extractor - Extract Tags from Any Video | Optimizo',
                'meta_description' => 'Extract tags and keywords from any YouTube video instantly. Analyze competitor tags and improve your video SEO strategy.',
                'meta_keywords' => 'youtube tags extractor, video tags, youtube keywords, extract tags, video seo',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 30,
            ],
            [
                'name' => 'YouTube Channel ID Finder',
                'slug' => 'youtube-channel-id-finder',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\ChannelIdFinderController',
                'route_name' => 'youtube.channel-id',
                'url' => '/tools/youtube-channel-id-finder',
                'meta_title' => 'Free YouTube Channel ID Finder - Find Any Channel ID | Optimizo',
                'meta_description' => 'Find YouTube channel ID from channel URL or username instantly. Essential for API integration and analytics.',
                'meta_keywords' => 'youtube channel id, find channel id, youtube api, channel id finder',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 31,
            ],
            [
                'name' => 'YouTube Earnings Calculator',
                'slug' => 'youtube-earnings-calculator',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\EarningsCalculatorController',
                'route_name' => 'youtube.earnings',
                'url' => '/tools/youtube-earnings-calculator',
                'meta_title' => 'Free YouTube Earnings Calculator - Estimate YouTube Revenue | Optimizo',
                'meta_description' => 'Calculate estimated YouTube earnings based on views, CPM, and engagement. Free YouTube revenue calculator.',
                'meta_keywords' => 'youtube earnings calculator, youtube revenue, calculate youtube income, cpm calculator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 32,
            ],

            // Network Tools
            [
                'name' => 'IP Lookup',
                'slug' => 'ip-lookup',
                'category' => 'network',
                'controller' => 'Tools\Network\IpLookupController',
                'route_name' => 'network.ip-lookup',
                'url' => '/tools/ip-lookup',
                'meta_title' => 'Free IP Lookup Tool - Get IP Address Details | Optimizo',
                'meta_description' => 'Lookup any IP address to get detailed information including location, ISP, hostname, and more.',
                'meta_keywords' => 'ip lookup, ip address lookup, ip geolocation, ip details',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 33,
            ],
            [
                'name' => 'DNS Lookup',
                'slug' => 'dns-lookup',
                'category' => 'network',
                'controller' => 'Tools\Network\DnsLookupController',
                'route_name' => 'network.dns-lookup',
                'url' => '/tools/dns-lookup',
                'meta_title' => 'Free DNS Lookup Tool - Check DNS Records | Optimizo',
                'meta_description' => 'Lookup DNS records for any domain including A, MX, NS, TXT, and CNAME records.',
                'meta_keywords' => 'dns lookup, dns records, domain lookup, mx records',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 34,
            ],
            [
                'name' => 'WHOIS Lookup',
                'slug' => 'whois-lookup',
                'category' => 'network',
                'controller' => 'Tools\Network\WhoisLookupController',
                'route_name' => 'network.whois-lookup',
                'url' => '/tools/whois-lookup',
                'meta_title' => 'Free WHOIS Lookup Tool - Domain Registration Info | Optimizo',
                'meta_description' => 'Get WHOIS information for any domain including registration date, registrar, and nameservers.',
                'meta_keywords' => 'whois lookup, domain whois, domain registration, whois search',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 35,
            ],
            [
                'name' => 'Ping Test',
                'slug' => 'ping-test',
                'category' => 'network',
                'controller' => 'Tools\Network\PingTestController',
                'route_name' => 'network.ping-test',
                'url' => '/tools/ping-test',
                'meta_title' => 'Free Ping Test Tool - Test Network Connectivity | Optimizo',
                'meta_description' => 'Test network connectivity and latency to any host with our free ping tool.',
                'meta_keywords' => 'ping test, network ping, connectivity test, latency test',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 36,
            ],
            [
                'name' => 'Traceroute',
                'slug' => 'traceroute',
                'category' => 'network',
                'controller' => 'Tools\Network\TracerouteController',
                'route_name' => 'network.traceroute',
                'url' => '/tools/traceroute',
                'meta_title' => 'Free Traceroute Tool - Trace Network Route | Optimizo',
                'meta_description' => 'Trace the route packets take to reach a destination and identify network hops.',
                'meta_keywords' => 'traceroute, trace route, network path, network hops',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 37,
            ],
            [
                'name' => 'Port Checker',
                'slug' => 'port-checker',
                'category' => 'network',
                'controller' => 'Tools\Network\PortCheckerController',
                'route_name' => 'network.port-checker',
                'url' => '/tools/port-checker',
                'meta_title' => 'Free Port Checker Tool - Check Open Ports | Optimizo',
                'meta_description' => 'Check if a specific port is open on any server or IP address.',
                'meta_keywords' => 'port checker, open port checker, port scan, check port',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 38,
            ],
            [
                'name' => 'Reverse DNS Lookup',
                'slug' => 'reverse-dns',
                'category' => 'network',
                'controller' => 'Tools\Network\ReverseDnsController',
                'route_name' => 'network.reverse-dns',
                'url' => '/tools/reverse-dns',
                'meta_title' => 'Free Reverse DNS Lookup - Find Hostname from IP | Optimizo',
                'meta_description' => 'Perform reverse DNS lookup to find the hostname associated with an IP address.',
                'meta_keywords' => 'reverse dns, reverse dns lookup, ip to hostname, ptr record',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 39,
            ],
        ];

        foreach ($tools as $tool) {
            Tool::create($tool);
        }
    }
}
