<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tool;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing tools
        \Illuminate\Support\Facades\DB::table('tools')->truncate();

        $tools = [
            // Image Tools
            [
                'name' => 'Image Converter',
                'slug' => 'image-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.image-converter',
                'url' => '/tools/image-converter',
                'meta_title' => 'Free Image Converter - Convert Images Online | Optimizo',
                'meta_description' => 'Convert images between multiple formats (JPG, PNG, WebP, BMP, TIFF) online for free. Fast and secure image conversion tool.',
                'meta_keywords' => 'image converter, convert images, jpg to png, png to jpg, webp converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 100,
            ],
            [
                'name' => 'JPG to PNG Converter',
                'slug' => 'jpg-to-png-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.jpg-to-png',
                'url' => '/tools/jpg-to-png-converter',
                'meta_title' => 'JPG to PNG Converter - Convert JPG Images to PNG | Optimizo',
                'meta_description' => 'Convert JPG images to PNG format instantly. Free online JPG to PNG converter with high quality output.',
                'meta_keywords' => 'jpg to png, convert jpg to png, jpg png converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 101,
            ],
            [
                'name' => 'PNG to JPG Converter',
                'slug' => 'png-to-jpg-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.png-to-jpg',
                'url' => '/tools/png-to-jpg-converter',
                'meta_title' => 'PNG to JPG Converter - Convert PNG Images to JPG | Optimizo',
                'meta_description' => 'Convert PNG images to JPG format instantly. Free online PNG to JPG converter.',
                'meta_keywords' => 'png to jpg, convert png to jpg, png jpg converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 102,
            ],
            [
                'name' => 'JPG to WebP Converter',
                'slug' => 'jpg-to-webp-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.jpg-to-webp',
                'url' => '/tools/jpg-to-webp-converter',
                'meta_title' => 'JPG to WebP Converter - Convert JPG to WebP | Optimizo',
                'meta_description' => 'Convert JPG images to WebP format for better web performance. Free online JPG to WebP converter.',
                'meta_keywords' => 'jpg to webp, convert jpg to webp, webp converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 103,
            ],
            [
                'name' => 'WebP to JPG Converter',
                'slug' => 'webp-to-jpg-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.webp-to-jpg',
                'url' => '/tools/webp-to-jpg-converter',
                'meta_title' => 'WebP to JPG Converter - Convert WebP to JPG | Optimizo',
                'meta_description' => 'Convert WebP images to JPG format. Restore WebP images to standard JPG format for free.',
                'meta_keywords' => 'webp to jpg, convert webp to jpg, webp decoder',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 104,
            ],
            [
                'name' => 'PNG to WebP Converter',
                'slug' => 'png-to-webp-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.png-to-webp',
                'url' => '/tools/png-to-webp-converter',
                'meta_title' => 'PNG to WebP Converter - Convert PNG to WebP | Optimizo',
                'meta_description' => 'Convert PNG images to WebP format with transparency support. Optimize PNGs for the web.',
                'meta_keywords' => 'png to webp, convert png to webp, png webp converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 105,
            ],
            [
                'name' => 'Image to Base64',
                'slug' => 'image-to-base64-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.image-to-base64',
                'url' => '/tools/image-to-base64-converter',
                'meta_title' => 'Image to Base64 Converter - Convert Image to Base64 String | Optimizo',
                'meta_description' => 'Convert images to Base64 strings. Embed images directly in HTML/CSS with Base64 encoding.',
                'meta_keywords' => 'image to base64, base64 converter, image encoder',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 106,
            ],
            [
                'name' => 'Base64 to Image',
                'slug' => 'base64-to-image-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.base64-to-image',
                'url' => '/tools/base64-to-image-converter',
                'meta_title' => 'Base64 to Image Converter - Convert Base64 String to Image | Optimizo',
                'meta_description' => 'Convert various Base64 strings back to image files. Decode Base64 images for free.',
                'meta_keywords' => 'base64 to image, base64 decoder, image decoder',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 107,
            ],
            [
                'name' => 'SVG to PNG Converter',
                'slug' => 'svg-to-png-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.svg-to-png',
                'url' => '/tools/svg-to-png-converter',
                'meta_title' => 'SVG to PNG Converter - Convert SVG to PNG High Quality | Optimizo',
                'meta_description' => 'Convert SVG vector files to PNG images. Rasterize SVGs with high quality preservation.',
                'meta_keywords' => 'svg to png, convert svg to png, svg converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 108,
            ],
            [
                'name' => 'SVG to JPG Converter',
                'slug' => 'svg-to-jpg-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.svg-to-jpg',
                'url' => '/tools/svg-to-jpg-converter',
                'meta_title' => 'SVG to JPG Converter - Convert SVG to JPG | Optimizo',
                'meta_description' => 'Convert SVG vector files to JPG images. Free online SVG to JPG converter.',
                'meta_keywords' => 'svg to jpg, convert svg to jpg, svg rasterizer',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 109,
            ],
            [
                'name' => 'HEIC to JPG Converter',
                'slug' => 'heic-to-jpg-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.heic-to-jpg',
                'url' => '/tools/heic-to-jpg-converter',
                'meta_title' => 'HEIC to JPG Converter - Convert iPhone Photos to JPG | Optimizo',
                'meta_description' => 'Convert HEIC/HEIF images (iPhone photos) to JPG format. View and share HEIC photos anywhere.',
                'meta_keywords' => 'heic to jpg, convert heic, iphone photo converter, heic converter',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 110,
            ],
            [
                'name' => 'ICO Converter',
                'slug' => 'ico-converter',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.ico-converter',
                'url' => '/tools/ico-converter',
                'meta_title' => 'ICO Converter - Create Favicons & Icons | Optimizo',
                'meta_description' => 'Convert images to ICO format. Create favicons for websites and icons for applications.',
                'meta_keywords' => 'ico converter, create favicon, image to ico, icon generator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 111,
            ],

            // Network Tools
            [
                'name' => 'What Is My IP',
                'slug' => 'what-is-my-ip',
                'category' => 'network',
                'subcategory' => 'IP Tools',
                'controller' => 'Tools\Network\WhatIsMyIpController',
                'route_name' => 'network.what-is-my-ip',
                'url' => '/tools/what-is-my-ip',
                'meta_title' => 'What Is My IP Address? - Check Your Public IP | Optimizo',
                'meta_description' => 'Find your public IP address instantly. Check your IPv4 and IPv6 address, location, ISP, and network information for free.',
                'meta_keywords' => 'what is my ip, check ip address, find my ip, public ip, ipv4, ipv6',
                'priority' => 0.9,
                'change_frequency' => 'daily',
                'order' => 1,
            ],
            [
                'name' => 'What Is My ISP',
                'slug' => 'what-is-my-isp',
                'category' => 'network',
                'subcategory' => 'IP Tools',
                'controller' => 'Tools\Network\WhatIsMyIspController',
                'route_name' => 'network.what-is-my-isp',
                'url' => '/tools/what-is-my-isp',
                'meta_title' => 'What Is My ISP? - Check Your Internet Service Provider | Optimizo',
                'meta_description' => 'Find your Internet Service Provider (ISP) instantly. Check your ISP name, ASN, organization, and network details for free.',
                'meta_keywords' => 'what is my isp, check isp, internet service provider, asn, network provider',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 2,
            ],
            [
                'name' => 'Domain to IP',
                'slug' => 'domain-to-ip',
                'category' => 'network',
                'subcategory' => 'Domain Tools',
                'controller' => 'Tools\Network\DomainToIpController',
                'route_name' => 'network.domain-to-ip',
                'url' => '/tools/domain-to-ip',
                'meta_title' => 'Domain to IP Converter - Find IP Address of Any Domain | Optimizo',
                'meta_description' => 'Convert domain names to IP addresses instantly. Find the IP address of any website or domain for free.',
                'meta_keywords' => 'domain to ip, dns lookup, find ip address, domain ip converter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 3,
            ],

            // Utility Tools
            [
                'name' => 'Internet Speed Test',
                'slug' => 'internet-speed-test',
                'category' => 'utility',
                'subcategory' => 'Network Diagnostics',
                'controller' => 'Tools\Utility\InternetSpeedTestController',
                'route_name' => 'utility.speed-test',
                'url' => '/tools/internet-speed-test',
                'meta_title' => 'Free Internet Speed Test - Check Your Connection Speed | Optimizo',
                'meta_description' => 'Test your internet speed for free. Check download speed, upload speed, ping, and jitter instantly.',
                'meta_keywords' => 'internet speed test, speed test, bandwidth test, connection speed',
                'priority' => 0.9,
                'change_frequency' => 'daily',
                'order' => 4,
            ],
            [
                'name' => 'Image Compressor',
                'slug' => 'image-compressor',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\ImageCompressorController',
                'route_name' => 'utility.image-compressor',
                'url' => '/tools/image-compressor',
                'meta_title' => 'Free Image Compressor - Compress Images Online | Optimizo',
                'meta_description' => 'Compress JPG, PNG, and WebP images online for free. Reduce file size while maintaining quality. Fast, secure, and easy to use.',
                'meta_keywords' => 'image compressor, compress images, reduce image size, optimize images',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 5,
            ],
            [
                'name' => 'RGB to HEX Converter',
                'slug' => 'rgb-hex-converter',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\RgbHexConverterController',
                'route_name' => 'utility.rgb-hex-converter',
                'url' => '/tools/rgb-hex-converter',
                'meta_title' => 'RGB to HEX Converter - Convert Colors Online | Optimizo',
                'meta_description' => 'Convert RGB to HEX and HEX to RGB color codes instantly. Free online color converter for web designers and developers.',
                'meta_keywords' => 'rgb to hex, hex to rgb, color converter, rgb converter, hex converter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 6,
            ],
            [
                'name' => 'Slug Generator',
                'slug' => 'slug-generator',
                'category' => 'utility',
                'subcategory' => 'Text Tools',
                'controller' => 'Tools\Utility\SlugGeneratorController',
                'route_name' => 'utility.slug-generator',
                'url' => '/tools/slug-generator',
                'meta_title' => 'Free Slug Generator - Create SEO-Friendly URLs | Optimizo',
                'meta_description' => 'Generate SEO-friendly URL slugs from any text. Create clean, readable URLs for better search engine optimization.',
                'meta_keywords' => 'slug generator, url slug, seo url, permalink generator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 7,
            ],
            [
                'name' => 'MD5 Generator',
                'slug' => 'md5-generator',
                'category' => 'utility',
                'subcategory' => 'Security Tools',
                'controller' => 'Tools\Utility\Md5GeneratorController',
                'route_name' => 'utility.md5-generator',
                'url' => '/tools/md5-generator',
                'meta_title' => 'Free MD5 Hash Generator - Generate MD5 Online | Optimizo',
                'meta_description' => 'Generate MD5 hash from any text instantly. Free online MD5 generator for checksums and data integrity verification.',
                'meta_keywords' => 'md5 generator, md5 hash, checksum, hash generator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 8,
            ],
            [
                'name' => 'Case Converter',
                'slug' => 'case-converter',
                'category' => 'utility',
                'subcategory' => 'Text Tools',
                'controller' => 'Tools\Utility\CaseConverterController',
                'route_name' => 'utility.case-converter',
                'url' => '/tools/case-converter',
                'meta_title' => 'Free Case Converter - Convert Text Case Online | Optimizo',
                'meta_description' => 'Convert text to uppercase, lowercase, title case, sentence case, and more. Free online text case converter.',
                'meta_keywords' => 'case converter, text converter, uppercase, lowercase, title case',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 9,
            ],
            [
                'name' => 'Username Checker',
                'slug' => 'username-checker',
                'category' => 'utility',
                'subcategory' => 'Social Tools',
                'controller' => 'Tools\Utility\UsernameCheckerController',
                'route_name' => 'utility.username-checker',
                'url' => '/tools/username-checker',
                'meta_title' => 'Username Availability Checker - Check Username Across Platforms | Optimizo',
                'meta_description' => 'Check username availability across multiple social media platforms instantly. Find available usernames for your brand.',
                'meta_keywords' => 'username checker, check username, username availability, social media username',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 10,
            ],
            [
                'name' => 'Password Generator',
                'slug' => 'password-generator',
                'category' => 'utility',
                'subcategory' => 'Security Tools',
                'controller' => 'Tools\Utility\PasswordGeneratorController',
                'route_name' => 'utility.password-generator',
                'url' => '/tools/password-generator',
                'meta_title' => 'Free Password Generator - Create Strong Passwords | Optimizo',
                'meta_description' => 'Generate strong, secure passwords instantly. Customize length, characters, and complexity for maximum security.',
                'meta_keywords' => 'password generator, strong password, secure password, random password',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 11,
            ],
            [
                'name' => 'JSON Formatter',
                'slug' => 'json-formatter',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\JsonFormatterController',
                'route_name' => 'utility.json-formatter',
                'url' => '/tools/json-formatter',
                'meta_title' => 'Free JSON Formatter - Beautify & Validate JSON Online | Optimizo',
                'meta_description' => 'Format, beautify, and validate JSON data online. Free JSON formatter with syntax highlighting and error detection.',
                'meta_keywords' => 'json formatter, json beautifier, json validator, format json',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 12,
            ],
            [
                'name' => 'Base64 Encoder/Decoder',
                'slug' => 'base64-encoder-decoder',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\Base64Controller',
                'route_name' => 'utility.base64',
                'url' => '/tools/base64-encoder-decoder',
                'meta_title' => 'Free Base64 Encoder & Decoder - Encode & Decode Base64 Online | Optimizo',
                'meta_description' => 'Free online Base64 encoder and decoder. Encode text to Base64 or decode Base64 to text instantly. Perfect for developers and API testing.',
                'meta_keywords' => 'base64 encoder, base64 decoder, encode base64, decode base64',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 13,
            ],
            [
                'name' => 'QR Code Generator',
                'slug' => 'qr-code-generator',
                'category' => 'utility',
                'subcategory' => 'Image Tools',
                'controller' => 'Tools\Utility\QrGeneratorController',
                'route_name' => 'utility.qr-generator',
                'url' => '/tools/qr-code-generator',
                'meta_title' => 'Free QR Code Generator - Create QR Codes Online | Optimizo',
                'meta_description' => 'Generate QR codes for URLs, text, and more. Free online QR code generator with multiple sizes and instant download.',
                'meta_keywords' => 'qr code generator, create qr code, qr generator, free qr code',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 14,
            ],
            [
                'name' => 'HTML Viewer',
                'slug' => 'html-viewer',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\HtmlViewerController',
                'route_name' => 'utility.html-viewer',
                'url' => '/tools/html-viewer',
                'meta_title' => 'Free HTML Viewer - Preview HTML Code Online | Optimizo',
                'meta_description' => 'View and preview HTML code in real-time. Free online HTML viewer with live preview and syntax highlighting.',
                'meta_keywords' => 'html viewer, html preview, view html, html code viewer',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 15,
            ],
            [
                'name' => 'JSON Parser',
                'slug' => 'json-parser',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\JsonParserController',
                'route_name' => 'utility.json-parser',
                'url' => '/tools/json-parser',
                'meta_title' => 'Free JSON Parser - Parse & Validate JSON Online | Optimizo',
                'meta_description' => 'Parse and validate JSON data online. Free JSON parser with tree view, syntax validation, and error detection.',
                'meta_keywords' => 'json parser, parse json, validate json, json validator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 16,
            ],

            // YouTube Tools
            [
                'name' => 'YouTube Monetization Checker',
                'slug' => 'youtube-monetization-checker',
                'category' => 'youtube',
                'subcategory' => 'Monetization & Analytics',
                'controller' => 'Tools\YouTube\MonetizationCheckerController',
                'route_name' => 'youtube.monetization',
                'url' => '/tools/youtube-monetization-checker',
                'meta_title' => 'YouTube Monetization Checker - Check Channel Eligibility | Optimizo',
                'meta_description' => 'Check if a YouTube channel is monetized. Verify monetization status, subscriber count, and eligibility instantly.',
                'meta_keywords' => 'youtube monetization checker, check monetization, youtube eligibility',
                'priority' => 0.9,
                'change_frequency' => 'daily',
                'order' => 17,
            ],
            [
                'name' => 'YouTube Thumbnail Downloader',
                'slug' => 'youtube-thumbnail-downloader',
                'category' => 'youtube',
                'subcategory' => 'Video Tools',
                'controller' => 'Tools\YouTube\ThumbnailDownloaderController',
                'route_name' => 'youtube.thumbnail',
                'url' => '/tools/youtube-thumbnail-downloader',
                'meta_title' => 'YouTube Thumbnail Downloader - Download HD Thumbnails | Optimizo',
                'meta_description' => 'Download YouTube video thumbnails in HD quality. Get thumbnails in all sizes (SD, HD, Full HD, Max Res) for free.',
                'meta_keywords' => 'youtube thumbnail downloader, download thumbnail, youtube thumbnail',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 18,
            ],
            [
                'name' => 'YouTube Video Data Extractor',
                'slug' => 'youtube-video-data-extractor',
                'category' => 'youtube',
                'subcategory' => 'Video Tools',
                'controller' => 'Tools\YouTube\VideoDataExtractorController',
                'route_name' => 'youtube.extractor',
                'url' => '/tools/youtube-video-data-extractor',
                'meta_title' => 'YouTube Video Data Extractor - Extract Video Information | Optimizo',
                'meta_description' => 'Extract YouTube video data including title, description, tags, views, likes, and more. Free video data extractor.',
                'meta_keywords' => 'youtube data extractor, video data, youtube info, extract video data',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 19,
            ],
            [
                'name' => 'YouTube Tags Generator',
                'slug' => 'youtube-tag-generator',
                'category' => 'youtube',
                'subcategory' => 'Video Tools',
                'controller' => 'Tools\YouTube\TagsGeneratorController',
                'route_name' => 'youtube.tags',
                'url' => '/tools/youtube-tag-generator',
                'meta_title' => 'YouTube Tags Generator - Generate Video Tags for SEO | Optimizo',
                'meta_description' => 'Generate optimized YouTube tags for better video SEO. Extract tags from competitors and boost your video visibility.',
                'meta_keywords' => 'youtube tags generator, video tags, youtube seo, generate tags',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 20,
            ],
            [
                'name' => 'YouTube Channel Data Extractor',
                'slug' => 'youtube-channel-data-extractor',
                'category' => 'youtube',
                'subcategory' => 'Channel Tools',
                'controller' => 'Tools\YouTube\ChannelDataExtractorController',
                'route_name' => 'youtube.channel',
                'url' => '/tools/youtube-channel-data-extractor',
                'meta_title' => 'YouTube Channel Data Extractor - Extract Channel Information | Optimizo',
                'meta_description' => 'Extract YouTube channel data including subscribers, views, videos, and more. Free channel data extractor.',
                'meta_keywords' => 'youtube channel extractor, channel data, youtube stats, extract channel info',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 21,
            ],
            [
                'name' => 'YouTube Handle Checker',
                'slug' => 'youtube-handle-checker',
                'category' => 'youtube',
                'subcategory' => 'Channel Tools',
                'controller' => 'Tools\YouTube\HandleCheckerController',
                'route_name' => 'youtube.handle',
                'url' => '/tools/youtube-handle-checker',
                'meta_title' => 'YouTube Handle Availability Checker - Check @Username | Optimizo',
                'meta_description' => 'Check if your desired YouTube handle (@username) is available. Instantly verify YouTube username availability for your channel.',
                'meta_keywords' => 'youtube handle checker, check handle, youtube username, handle availability',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 22,
            ],

            // SEO Tools
            [
                'name' => 'Meta Tag Analyzer',
                'slug' => 'meta-tag-analyzer',
                'category' => 'seo',
                'subcategory' => 'Analysis Tools',
                'controller' => 'Tools\SEO\MetaAnalyzerController',
                'route_name' => 'seo.meta-analyzer',
                'url' => '/tools/meta-tag-analyzer',
                'meta_title' => 'Free Meta Tag Analyzer - Analyze Meta Tags for SEO | Optimizo',
                'meta_description' => 'Analyze meta tags for SEO optimization. Check title tags, meta descriptions, Open Graph, and Twitter Cards instantly.',
                'meta_keywords' => 'meta tag analyzer, seo analyzer, meta tags, analyze meta tags',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 23,
            ],
            [
                'name' => 'Keyword Density Checker',
                'slug' => 'keyword-density-checker',
                'category' => 'seo',
                'subcategory' => 'Keyword Tools',
                'controller' => 'Tools\SEO\KeywordDensityController',
                'route_name' => 'seo.keyword-density',
                'url' => '/tools/keyword-density-checker',
                'meta_title' => 'Free Keyword Density Checker - Analyze Keyword Frequency for SEO | Optimizo',
                'meta_description' => 'Free keyword density checker. Analyze keyword frequency and density in your content for better SEO optimization.',
                'meta_keywords' => 'keyword density checker, keyword frequency, seo keyword analysis',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 24,
            ],
            [
                'name' => 'Word Counter',
                'slug' => 'word-counter',
                'category' => 'seo',
                'subcategory' => 'Analysis Tools',
                'controller' => 'Tools\SEO\WordCounterController',
                'route_name' => 'seo.word-counter',
                'url' => '/tools/word-counter',
                'meta_title' => 'Free Word Counter - Count Words, Characters & Reading Time | Optimizo',
                'meta_description' => 'Free online word counter tool. Count words, characters, sentences, paragraphs, and estimate reading time instantly.',
                'meta_keywords' => 'word counter, character counter, count words, reading time',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 25,
            ],
            [
                'name' => 'Redirect & HTTP Status Checker',
                'slug' => 'redirect-checker',
                'category' => 'seo',
                'subcategory' => 'Technical SEO',
                'controller' => 'Tools\Network\RedirectCheckerController',
                'route_name' => 'network.redirect-checker',
                'url' => '/tools/redirect-checker',
                'meta_title' => 'Redirect Checker & HTTP Status Code Tool - Free Online',
                'meta_description' => 'Free redirect checker tool to analyze HTTP status codes, trace redirect chains, detect 301/302 redirects, find broken redirects and redirect loops. Essential for SEO and website debugging.',
                'meta_keywords' => 'redirect checker, http status code, 301 redirect, 302 redirect, redirect loop, broken links, seo tool',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 26,
            ],

            // New Utility Tools
            [
                'name' => 'Code Formatter',
                'slug' => 'code-formatter',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\CodeFormatterController',
                'route_name' => 'utility.code-formatter',
                'url' => '/tools/code-formatter',
                'meta_title' => 'Free Code Formatter - Format & Beautify Code Online | Optimizo',
                'meta_description' => 'Format and beautify code in multiple languages. Support for HTML, CSS, JavaScript, PHP, Python, Java, C++, and JSON. Free online code formatter.',
                'meta_keywords' => 'code formatter, beautify code, format code, code beautifier, minify code',
                'priority' => 0.9,
                'change_frequency' => 'weekly',
                'order' => 27,
            ],
            [
                'name' => 'CSS Minifier',
                'slug' => 'css-minifier',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\CssMinifierController',
                'route_name' => 'utility.css-minifier',
                'url' => '/tools/css-minifier',
                'meta_title' => 'Free CSS Minifier - Minify & Beautify CSS Online | Optimizo',
                'meta_description' => 'Minify CSS to reduce file size or beautify CSS for better readability. Free online CSS minifier and formatter tool.',
                'meta_keywords' => 'css minifier, minify css, css compressor, beautify css, css formatter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 27,
            ],
            [
                'name' => 'JavaScript Minifier',
                'slug' => 'js-minifier',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\JsMinifierController',
                'route_name' => 'utility.js-minifier',
                'url' => '/tools/js-minifier',
                'meta_title' => 'Free JavaScript Minifier - Minify & Beautify JS Online | Optimizo',
                'meta_description' => 'Minify JavaScript to reduce file size or beautify JS for better readability. Free online JavaScript minifier and formatter tool.',
                'meta_keywords' => 'javascript minifier, minify js, js compressor, beautify javascript, js formatter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 28,
            ],
            [
                'name' => 'HTML Minifier',
                'slug' => 'html-minifier',
                'category' => 'utility',
                'subcategory' => 'Dev Tools',
                'controller' => 'Tools\Utility\HtmlMinifierController',
                'route_name' => 'utility.html-minifier',
                'url' => '/tools/html-minifier',
                'meta_title' => 'Free HTML Minifier - Minify & Beautify HTML Online | Optimizo',
                'meta_description' => 'Minify HTML to reduce file size or beautify HTML for better readability. Free online HTML minifier and formatter tool.',
                'meta_keywords' => 'html minifier, minify html, html compressor, beautify html, html formatter',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 29,
            ],

            // New YouTube Tools
            [
                'name' => 'YouTube Video Tags Extractor',
                'slug' => 'youtube-video-tags-extractor',
                'category' => 'youtube',
                'subcategory' => 'Video Tools',
                'controller' => 'Tools\YouTube\VideoTagsExtractorController',
                'route_name' => 'youtube.video-tags',
                'url' => '/tools/youtube-video-tags-extractor',
                'meta_title' => 'Free YouTube Video Tags Extractor - Extract Tags from Any Video | Optimizo',
                'meta_description' => 'Extract tags and keywords from any YouTube video instantly. Analyze competitor tags and improve your video SEO strategy.',
                'meta_keywords' => 'youtube tags extractor, video tags, youtube keywords, extract tags, video seo',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 30,
            ],
            [
                'name' => 'YouTube Channel ID Finder',
                'slug' => 'youtube-channel-id-finder',
                'category' => 'youtube',
                'subcategory' => 'Channel Tools',
                'controller' => 'Tools\YouTube\ChannelIdFinderController',
                'route_name' => 'youtube.channel-id',
                'url' => '/tools/youtube-channel-id-finder',
                'meta_title' => 'Free YouTube Channel ID Finder - Find Any Channel ID | Optimizo',
                'meta_description' => 'Find YouTube channel ID from channel URL or username instantly. Essential for API integration and analytics.',
                'meta_keywords' => 'youtube channel id, find channel id, youtube api, channel id finder',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 31,
            ],
            [
                'name' => 'YouTube Earnings Calculator',
                'slug' => 'youtube-earnings-calculator',
                'category' => 'youtube',
                'subcategory' => 'Monetization & Analytics',
                'controller' => 'Tools\YouTube\EarningsCalculatorController',
                'route_name' => 'youtube.earnings',
                'url' => '/tools/youtube-earnings-calculator',
                'meta_title' => 'Free YouTube Earnings Calculator - Estimate YouTube Revenue | Optimizo',
                'meta_description' => 'Calculate estimated YouTube earnings based on views, CPM, and engagement. Free YouTube revenue calculator.',
                'meta_keywords' => 'youtube earnings calculator, youtube revenue, calculate youtube income, cpm calculator',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 32,
            ],

            // Network Tools
            [
                'name' => 'IP Lookup',
                'slug' => 'ip-lookup',
                'category' => 'network',
                'subcategory' => 'IP Tools',
                'controller' => 'Tools\Network\IpLookupController',
                'route_name' => 'network.ip-lookup',
                'url' => '/tools/ip-lookup',
                'meta_title' => 'Free IP Lookup Tool - Get IP Address Details | Optimizo',
                'meta_description' => 'Lookup any IP address to get detailed information including location, ISP, hostname, and more.',
                'meta_keywords' => 'ip lookup, ip address lookup, ip geolocation, ip details',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 33,
            ],
            [
                'name' => 'DNS Lookup',
                'slug' => 'dns-lookup',
                'category' => 'network',
                'subcategory' => 'Domain Tools',
                'controller' => 'Tools\Network\DnsLookupController',
                'route_name' => 'network.dns-lookup',
                'url' => '/tools/dns-lookup',
                'meta_title' => 'Free DNS Lookup Tool - Check DNS Records | Optimizo',
                'meta_description' => 'Lookup DNS records for any domain including A, MX, NS, TXT, and CNAME records.',
                'meta_keywords' => 'dns lookup, dns records, domain lookup, mx records',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 34,
            ],
            [
                'name' => 'WHOIS Lookup',
                'slug' => 'whois-lookup',
                'category' => 'network',
                'subcategory' => 'Domain Tools',
                'controller' => 'Tools\Network\WhoisLookupController',
                'route_name' => 'network.whois-lookup',
                'url' => '/tools/whois-lookup',
                'meta_title' => 'Free WHOIS Lookup Tool - Domain Registration Info | Optimizo',
                'meta_description' => 'Get WHOIS information for any domain including registration date, registrar, and nameservers.',
                'meta_keywords' => 'whois lookup, domain whois, domain registration, whois search',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 35,
            ],
            [
                'name' => 'Ping Test',
                'slug' => 'ping-test',
                'category' => 'network',
                'subcategory' => 'Network Diagnostics',
                'controller' => 'Tools\Network\PingTestController',
                'route_name' => 'network.ping-test',
                'url' => '/tools/ping-test',
                'meta_title' => 'Free Ping Test Tool - Test Network Connectivity | Optimizo',
                'meta_description' => 'Test network connectivity and latency to any host with our free ping tool.',
                'meta_keywords' => 'ping test, network ping, connectivity test, latency test',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 36,
            ],
            [
                'name' => 'Traceroute',
                'slug' => 'traceroute',
                'category' => 'network',
                'subcategory' => 'Network Diagnostics',
                'controller' => 'Tools\Network\TracerouteController',
                'route_name' => 'network.traceroute',
                'url' => '/tools/traceroute',
                'meta_title' => 'Free Traceroute Tool - Trace Network Route | Optimizo',
                'meta_description' => 'Trace the route packets take to reach a destination and identify network hops.',
                'meta_keywords' => 'traceroute, trace route, network path, network hops',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 37,
            ],
            [
                'name' => 'Port Checker',
                'slug' => 'port-checker',
                'category' => 'network',
                'subcategory' => 'Network Diagnostics',
                'controller' => 'Tools\Network\PortCheckerController',
                'route_name' => 'network.port-checker',
                'url' => '/tools/port-checker',
                'meta_title' => 'Free Port Checker Tool - Check Open Ports | Optimizo',
                'meta_description' => 'Check if a specific port is open on any server or IP address.',
                'meta_keywords' => 'port checker, open port checker, port scan, check port',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 38,
            ],
            [
                'name' => 'Reverse DNS Lookup',
                'slug' => 'reverse-dns',
                'category' => 'network',
                'subcategory' => 'Domain Tools',
                'controller' => 'Tools\Network\ReverseDnsController',
                'route_name' => 'network.reverse-dns',
                'url' => '/tools/reverse-dns',
                'meta_title' => 'Free Reverse DNS Lookup - Find Hostname from IP | Optimizo',
                'meta_description' => 'Perform reverse DNS lookup to find the hostname associated with an IP address.',
                'meta_keywords' => 'reverse dns, reverse dns lookup, ip to hostname, ptr record',
                'priority' => 0.8,
                'change_frequency' => 'weekly',
                'order' => 39,
            ],
        
            // Consolidate Missing Tools
            [
                'slug' => 'ascii-converter',
                'name' => 'ASCII Converter',
                'category' => 'utility',
                'subcategory' => 'Encoding/Decoding Tools (JWT and ASCII only - others are combined above)',
                'controller' => 'EncodingController@asciiConvert',
                'route_name' => 'utility.ascii-convert',
                'url' => '/tools/ascii-converter',
                'meta_title' => 'ASCII Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert between ASCII and text. Encode text to ASCII codes or decode ASCII to text.',
                'priority' => 0.8,
                'order' => 34,
            ],
            [
                'slug' => 'binary-hex-converter',
                'name' => 'Binary to Hexadecimal Converter',
                'category' => 'utility',
                'subcategory' => 'Number System Converters',
                'controller' => 'Tools\\Utility\\BinaryHexController',
                'route_name' => 'utility.binary-hex',
                'url' => '/tools/binary-hex-converter',
                'meta_title' => 'Binary to Hexadecimal Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert binary numbers to hexadecimal and vice versa. Free bidirectional binary-hex converter.',
                'priority' => 0.8,
                'order' => 69,
            ],
            [
                'slug' => 'bing-serp-checker',
                'name' => 'Bing SERP Checker',
                'category' => 'seo',
                'subcategory' => 'Google SERP Checker',
                'controller' => 'Tools\\Seo\\BingSerpCheckerController',
                'route_name' => 'seo.bing-serp-checker',
                'url' => '/tools/bing-serp-checker',
                'meta_title' => 'Bing SERP Checker - Free Seo Tool | Optimizo',
                'meta_description' => 'Use our free Bing SERP checker to track your Bing ranking and position. Detailed Bing SERP analysis for desktop and mobile from any location.',
                'priority' => 0.8,
                'order' => 15,
            ],
            [
                'slug' => 'broken-links-checker',
                'name' => 'Broken Links Checker',
                'category' => 'seo',
                'subcategory' => 'Broken Links Checker',
                'controller' => 'Tools\\Seo\\BrokenLinksCheckerController',
                'route_name' => 'seo.broken-links-checker',
                'url' => '/tools/broken-links-checker',
                'meta_title' => 'Broken Links Checker - Free Seo Tool | Optimizo',
                'meta_description' => 'Scan your webpage for dead links (404 errors) to improve user experience and SEO rankings. Free online broken link checker tool.',
                'priority' => 0.8,
                'order' => 18,
            ],
            [
                'slug' => 'camel-case-converter',
                'name' => 'Camel Case Converter',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\CamelCaseController',
                'route_name' => 'utility.camel-case',
                'url' => '/tools/camel-case-converter',
                'meta_title' => 'Camel Case Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to camelCase format. Perfect for JavaScript and programming variable names.',
                'priority' => 0.8,
                'order' => 49,
            ],
            [
                'slug' => 'csv-to-xml-converter',
                'name' => 'CSV to XML Converter',
                'category' => 'utility',
                'subcategory' => 'Data Format Converters (Bidirectional)',
                'controller' => 'Tools\\Utility\\CsvXmlController',
                'route_name' => 'utility.csv-xml',
                'url' => '/tools/csv-to-xml-converter',
                'meta_title' => 'CSV to XML Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert CSV to XML and vice versa. Free bidirectional CSV-XML converter with custom element names.',
                'priority' => 0.8,
                'order' => 37,
            ],
            [
                'slug' => 'decimal-binary-converter',
                'name' => 'Decimal to Binary Converter',
                'category' => 'utility',
                'subcategory' => 'Number System Converters',
                'controller' => 'Tools\\Utility\\DecimalBinaryController',
                'route_name' => 'utility.decimal-binary',
                'url' => '/tools/decimal-binary-converter',
                'meta_title' => 'Decimal to Binary Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert decimal numbers to binary and vice versa. Free bidirectional decimal-binary converter.',
                'priority' => 0.8,
                'order' => 67,
            ],
            [
                'slug' => 'decimal-hex-converter',
                'name' => 'Decimal to Hexadecimal Converter',
                'category' => 'utility',
                'subcategory' => 'Number System Converters',
                'controller' => 'Tools\\Utility\\DecimalHexController',
                'route_name' => 'utility.decimal-hex',
                'url' => '/tools/decimal-hex-converter',
                'meta_title' => 'Decimal to Hexadecimal Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert decimal numbers to hexadecimal and vice versa. Free bidirectional decimal-hex converter.',
                'priority' => 0.8,
                'order' => 68,
            ],
            [
                'slug' => 'decimal-octal-converter',
                'name' => 'Decimal to Octal Converter',
                'category' => 'utility',
                'subcategory' => 'Number System Converters',
                'controller' => 'Tools\\Utility\\DecimalOctalController',
                'route_name' => 'utility.decimal-octal',
                'url' => '/tools/decimal-octal-converter',
                'meta_title' => 'Decimal to Octal Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert decimal numbers to octal and vice versa. Free bidirectional decimal-octal converter.',
                'priority' => 0.8,
                'order' => 70,
            ],
            [
                'slug' => 'google-serp-checker',
                'name' => 'Google SERP Checker',
                'category' => 'seo',
                'subcategory' => 'Google SERP Checker',
                'controller' => 'Tools\\Seo\\GoogleSerpCheckerController',
                'route_name' => 'seo.google-serp-checker',
                'url' => '/tools/google-serp-checker',
                'meta_title' => 'Google SERP Checker - Free Seo Tool | Optimizo',
                'meta_description' => 'Simulate Google search results for any location and device to check your rankings.',
                'priority' => 0.8,
                'order' => 14,
            ],
            [
                'slug' => 'html-encoder-decoder',
                'name' => 'HTML Encoder/Decoder',
                'category' => 'utility',
                'subcategory' => 'Broken Links Checker',
                'controller' => 'Tools\\Utility\\HtmlEncoderController',
                'route_name' => 'utility.html-encoder',
                'url' => '/tools/html-encoder-decoder',
                'meta_title' => 'HTML Encoder/Decoder - Free Utility Tool | Optimizo',
                'meta_description' => 'Encode and decode HTML entities to prevent XSS attacks.',
                'priority' => 0.8,
                'order' => 31,
            ],
            [
                'slug' => 'html-to-markdown-converter',
                'name' => 'HTML to Markdown Converter',
                'category' => 'utility',
                'subcategory' => 'Broken Links Checker',
                'controller' => 'ConverterController@htmlToMarkdown',
                'route_name' => 'utility.html-to-markdown',
                'url' => '/tools/html-to-markdown-converter',
                'meta_title' => 'HTML to Markdown Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert HTML code to clean Markdown format instantly. Perfect for documentation and content migration.',
                'priority' => 0.8,
                'order' => 45,
            ],
            [
                'slug' => 'json-to-sql-converter',
                'name' => 'JSON to SQL Converter',
                'category' => 'utility',
                'subcategory' => 'Data Format Converters (Bidirectional)',
                'controller' => 'Tools\\Utility\\JsonSqlController',
                'route_name' => 'utility.json-sql',
                'url' => '/tools/json-to-sql-converter',
                'meta_title' => 'JSON to SQL Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert JSON to SQL INSERT statements and vice versa. Free bidirectional JSON-SQL converter.',
                'priority' => 0.8,
                'order' => 38,
            ],
            [
                'slug' => 'json-to-xml-converter',
                'name' => 'JSON to XML Converter',
                'category' => 'utility',
                'subcategory' => 'Data Format Converters (Bidirectional)',
                'controller' => 'Tools\\Utility\\JsonXmlController',
                'route_name' => 'utility.json-xml',
                'url' => '/tools/json-to-xml-converter',
                'meta_title' => 'JSON to XML Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert JSON to XML and vice versa. Free bidirectional JSON-XML converter with formatting options.',
                'priority' => 0.8,
                'order' => 35,
            ],
            [
                'slug' => 'json-to-yaml-converter',
                'name' => 'JSON to YAML Converter',
                'category' => 'utility',
                'subcategory' => 'Data Format Converters (Bidirectional)',
                'controller' => 'Tools\\Utility\\JsonYamlController',
                'route_name' => 'utility.json-yaml',
                'url' => '/tools/json-to-yaml-converter',
                'meta_title' => 'JSON to YAML Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert JSON to YAML and vice versa. Free bidirectional JSON-YAML converter for configuration files.',
                'priority' => 0.8,
                'order' => 36,
            ],
            [
                'slug' => 'jwt-decoder',
                'name' => 'JWT Decoder',
                'category' => 'utility',
                'subcategory' => 'Encoding/Decoding Tools (JWT and ASCII only - others are combined above)',
                'controller' => 'EncodingController@jwtDecode',
                'route_name' => 'utility.jwt-decode',
                'url' => '/tools/jwt-decoder',
                'meta_title' => 'JWT Decoder - Free Utility Tool | Optimizo',
                'meta_description' => 'Decode and inspect JWT tokens. View header, payload, and signature of JSON Web Tokens.',
                'priority' => 0.8,
                'order' => 33,
            ],
            [
                'slug' => 'kebab-case-converter',
                'name' => 'Kebab Case Converter',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\KebabCaseController',
                'route_name' => 'utility.kebab-case',
                'url' => '/tools/kebab-case-converter',
                'meta_title' => 'Kebab Case Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to kebab-case format. Popular for URLs and CSS class names.',
                'priority' => 0.8,
                'order' => 52,
            ],
            [
                'slug' => 'markdown-to-html-converter',
                'name' => 'Markdown to HTML Converter',
                'category' => 'utility',
                'subcategory' => 'Broken Links Checker',
                'controller' => 'Tools\\Utility\\MarkdownToHtmlController',
                'route_name' => 'utility.markdown-to-html',
                'url' => '/tools/markdown-to-html-converter',
                'meta_title' => 'Markdown to HTML Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert Markdown to HTML instantly with live preview.',
                'priority' => 0.8,
                'order' => 44,
            ],
            [
                'slug' => 'morse-to-text-converter',
                'name' => 'Morse Code to Text',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\MorseToTextController',
                'route_name' => 'utility.morse-to-text',
                'url' => '/tools/morse-to-text-converter',
                'meta_title' => 'Morse Code to Text - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert Morse code to text. Decode Morse code messages instantly.',
                'priority' => 0.8,
                'order' => 56,
            ],
            [
                'slug' => 'number-base-converter',
                'name' => 'Number Base Converter',
                'category' => 'utility',
                'subcategory' => 'Number System Converters',
                'controller' => 'Tools\\Utility\\NumberBaseController',
                'route_name' => 'utility.number-base',
                'url' => '/tools/number-base-converter',
                'meta_title' => 'Number Base Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert numbers between any bases (2-36). Universal number base converter supporting binary, octal, decimal, hexadecimal, and more.',
                'priority' => 0.8,
                'order' => 71,
            ],
            [
                'slug' => 'on-page-seo-checker',
                'name' => 'On-Page SEO Checker',
                'category' => 'seo',
                'subcategory' => 'On-Page SEO Checker',
                'controller' => 'Tools\\Seo\\OnPageSeoCheckerController',
                'route_name' => 'seo.on-page-seo-checker',
                'url' => '/tools/on-page-seo-checker',
                'meta_title' => 'On-Page SEO Checker - Free Seo Tool | Optimizo',
                'meta_description' => 'Comprehensive On-Page SEO audit tool. Analyze topic intent, content quality, and technical SEO factors.',
                'priority' => 0.8,
                'order' => 17,
            ],
            [
                'slug' => 'pascal-case-converter',
                'name' => 'Pascal Case Converter',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\PascalCaseController',
                'route_name' => 'utility.pascal-case',
                'url' => '/tools/pascal-case-converter',
                'meta_title' => 'Pascal Case Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to PascalCase format. Ideal for class names and type definitions.',
                'priority' => 0.8,
                'order' => 50,
            ],
            [
                'slug' => 'sentence-case-converter',
                'name' => 'Sentence Case Converter',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\SentenceCaseController',
                'route_name' => 'utility.sentence-case',
                'url' => '/tools/sentence-case-converter',
                'meta_title' => 'Sentence Case Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to sentence case. Capitalize the first letter of each sentence automatically.',
                'priority' => 0.8,
                'order' => 48,
            ],
            [
                'slug' => 'snake-case-converter',
                'name' => 'Snake Case Converter',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\SnakeCaseController',
                'route_name' => 'utility.snake-case',
                'url' => '/tools/snake-case-converter',
                'meta_title' => 'Snake Case Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to snake_case format. Common in Python, Ruby, and database naming.',
                'priority' => 0.8,
                'order' => 51,
            ],
            [
                'slug' => 'studly-case-converter',
                'name' => 'Studly Case Converter',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\StudlyCaseController',
                'route_name' => 'utility.studly-case',
                'url' => '/tools/studly-case-converter',
                'meta_title' => 'Studly Case Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to StUdLy CaSe format. Create random capitalization patterns.',
                'priority' => 0.8,
                'order' => 53,
            ],
            [
                'slug' => 'text-reverser',
                'name' => 'Text Reverser',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\TextReverserController',
                'route_name' => 'utility.text-reverser',
                'url' => '/tools/text-reverser',
                'meta_title' => 'Text Reverser - Free Utility Tool | Optimizo',
                'meta_description' => 'Reverse text strings character by character. Flip text backwards instantly.',
                'priority' => 0.8,
                'order' => 54,
            ],
            [
                'slug' => 'text-to-morse-converter',
                'name' => 'Text to Morse Code',
                'category' => 'utility',
                'subcategory' => 'Text & String Converters',
                'controller' => 'Tools\\Utility\\TextToMorseController',
                'route_name' => 'utility.text-to-morse',
                'url' => '/tools/text-to-morse-converter',
                'meta_title' => 'Text to Morse Code - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert text to Morse code. Encode messages using international Morse code.',
                'priority' => 0.8,
                'order' => 55,
            ],
            [
                'slug' => 'tsv-to-csv-converter',
                'name' => 'TSV to CSV Converter',
                'category' => 'utility',
                'subcategory' => 'Data Format Converters (Bidirectional)',
                'controller' => 'Tools\\Utility\\TsvCsvController',
                'route_name' => 'utility.tsv-csv',
                'url' => '/tools/tsv-to-csv-converter',
                'meta_title' => 'TSV to CSV Converter - Free Utility Tool | Optimizo',
                'meta_description' => 'Convert TSV to CSV and vice versa. Free bidirectional TSV-CSV converter online.',
                'priority' => 0.8,
                'order' => 39,
            ],
            [
                'slug' => 'unicode-encoder-decoder',
                'name' => 'Unicode Encoder/Decoder',
                'category' => 'utility',
                'subcategory' => 'Broken Links Checker',
                'controller' => 'Tools\\Utility\\UnicodeEncoderController',
                'route_name' => 'utility.unicode-encoder',
                'url' => '/tools/unicode-encoder-decoder',
                'meta_title' => 'Unicode Encoder/Decoder - Free Utility Tool | Optimizo',
                'meta_description' => 'Encode and decode Unicode escape sequences for JavaScript and JSON.',
                'priority' => 0.8,
                'order' => 32,
            ],
            [
                'slug' => 'url-encoder-decoder',
                'name' => 'URL Encoder/Decoder',
                'category' => 'utility',
                'subcategory' => 'Broken Links Checker',
                'controller' => 'Tools\\Utility\\UrlEncoderController',
                'route_name' => 'utility.url-encoder',
                'url' => '/tools/url-encoder-decoder',
                'meta_title' => 'URL Encoder/Decoder - Free Utility Tool | Optimizo',
                'meta_description' => 'Encode and decode URLs.',
                'priority' => 0.8,
                'order' => 30,
            ],
            [
                'slug' => 'yahoo-serp-checker',
                'name' => 'Yahoo SERP Checker',
                'category' => 'seo',
                'subcategory' => 'Google SERP Checker',
                'controller' => 'Tools\\Seo\\YahooSerpCheckerController',
                'route_name' => 'seo.yahoo-serp-checker',
                'url' => '/tools/yahoo-serp-checker',
                'meta_title' => 'Yahoo SERP Checker - Free Seo Tool | Optimizo',
                'meta_description' => 'Use our free Yahoo SERP checker to track your Yahoo ranking and position. Detailed Yahoo SERP analysis for desktop and mobile.',
                'priority' => 0.8,
                'order' => 16,
            ],
];

        foreach ($tools as $tool) {
            Tool::create($tool);
        }
    }
}
