<?php

$category = 'development';
$locales = ['ru', 'es'];

$translations = [
    'ru' => [
        'unicode-encoder-decoder.editor.btn_process_encode' => 'Закодировать Unicode',
        'unicode-encoder-decoder.editor.ph_output' => 'Обработанный Unicode появится здесь...',
        'unicode-encoder-decoder.editor.label_input_decode' => 'Введите Unicode для декодирования',
        'unicode-encoder-decoder.editor.label_output_decoded' => 'Декодированный текст',
        'unicode-encoder-decoder.editor.btn_process_decode' => 'Декодировать Unicode',
        'unicode-encoder-decoder.content.what_title' => 'Что такое кодирование Unicode?',
        'unicode-encoder-decoder.content.what_desc' => 'Кодирование Unicode преобразует символы в соответствующие кодовые точки, часто представляемые как escape-последовательности типа \uXXXX. Это гарантирует правильное представление спецсимволов в средах, поддерживающих только ASCII.',
        'unicode-encoder-decoder.content.features_title' => 'Особенности',
        'unicode-encoder-decoder.content.features.bidirectional.title' => 'Двунаправленность',
        'unicode-encoder-decoder.content.features.bidirectional.desc' => 'Кодируйте в формат Unicode или декодируйте обратно',
        'unicode-encoder-decoder.content.features.privacy.title' => 'Приватность',
        'unicode-encoder-decoder.content.features.privacy.desc' => 'Вся обработка происходит в вашем браузере',
        'unicode-encoder-decoder.content.features.universal.title' => 'Универсальная поддержка',
        'unicode-encoder-decoder.content.features.universal.desc' => 'Работает со всеми символами и скриптами Unicode',
        'unicode-encoder-decoder.content.uses_title' => 'Случаи использования',
        'unicode-encoder-decoder.content.uses.programming.title' => 'Программирование',
        'unicode-encoder-decoder.content.uses.programming.desc' => 'Безопасное встраивание спецсимволов в JavaScript или Java.',
        'unicode-encoder-decoder.content.uses.data.title' => 'Сериализация данных',
        'unicode-encoder-decoder.content.uses.data.desc' => 'Надежная передача не-ASCII символов в JSON.',
        'unicode-encoder-decoder.content.how_to_title' => 'Как использовать',
        'unicode-encoder-decoder.content.how_to.step1.title' => 'Выберите режим',
        'unicode-encoder-decoder.content.how_to.step1.desc' => 'Выберите "Закодировать" или "Декодировать".',
        'unicode-encoder-decoder.content.how_to.step2.title' => 'Введите текст',
        'unicode-encoder-decoder.content.how_to.step2.desc' => 'Вставьте ваш текст или последовательности Unicode.',
        'unicode-encoder-decoder.content.how_to.step3.title' => 'Обработка',
        'unicode-encoder-decoder.content.how_to.step3.desc' => 'Нажмите кнопку кодирования или декодирования.',
        'unicode-encoder-decoder.content.examples_title' => 'Примеры Unicode',
        'unicode-encoder-decoder.content.examples.simple.title' => 'Простые/ASCII:',
        'unicode-encoder-decoder.content.examples.simple.desc' => 'Оригинал: "A" → Код: "\u0041"',
        'unicode-encoder-decoder.content.examples.special.title' => 'Спецсимволы:',
        'unicode-encoder-decoder.content.examples.special.desc' => 'Оригинал: "©" → Код: "\u00A9"',
        'unicode-encoder-decoder.content.faq_title' => 'Вопросы и ответы',
        'unicode-encoder-decoder.content.faq.q1' => 'Зачем использовать escape-последовательности Unicode?',
        'unicode-encoder-decoder.content.faq.a1' => 'Они позволяют представлять любой символ с помощью только ASCII, что гарантирует совместимость при передаче файлов.',
        'unicode-encoder-decoder.content.faq.q4' => 'Безопасно ли это?',
        'unicode-encoder-decoder.content.faq.a4' => 'Да, всё происходит локально в браузере.',
        'unicode-encoder-decoder.js.error_process' => '✗ Ошибка обработки Unicode: ',
        'unicode-encoder-decoder.js.success_copy' => '✓ Скопировано в буфер обмена',

        'url-encoder-decoder.editor.btn_process_encode' => 'Закодировать URL',
        'url-encoder-decoder.editor.ph_output' => 'Обработанный URL появится здесь...',
        'url-encoder-decoder.editor.label_input_decode' => 'Введите URL для декодирования',
        'url-encoder-decoder.editor.label_output_decoded' => 'Декодированный URL',
        'url-encoder-decoder.editor.btn_process_decode' => 'Декодировать URL',
        'url-encoder-decoder.content.p1' => 'Наш бесплатный URL Энкодер и Декодер помогает кодировать спецсимволы в URL для безопасной передачи через интернет или декодировать их обратно. 100% клиентская обработка гарантирует приватность.',
        'url-encoder-decoder.content.features_title' => 'Особенности',
        'url-encoder-decoder.content.features.bidirectional.title' => 'Двунаправленность',
        'url-encoder-decoder.content.features.copy.title' => 'Копирование в клик',
        'url-encoder-decoder.content.features.universal.title' => 'Универсальная поддержка',
        'url-encoder-decoder.content.uses_title' => 'Случаи использования',
        'url-encoder-decoder.content.uses.query.title' => 'Параметры запроса',
        'url-encoder-decoder.content.uses.query.desc' => 'Кодирование спецсимволов в строках запроса URL для API.',
        'url-encoder-decoder.content.how_to_title' => 'Как использовать',
        'url-encoder-decoder.content.how_to.step1.title' => 'Выберите режим',
        'url-encoder-decoder.content.how_to.step2.title' => 'Введите URL',
        'url-encoder-decoder.content.how_to.step3.title' => 'Обработка',
        'url-encoder-decoder.content.how_to.step4.title' => 'Копируйте результат',
        'url-encoder-decoder.content.examples_title' => 'Примеры кодирования URL',
        'url-encoder-decoder.content.examples.space.title' => 'Пробел:',
        'url-encoder-decoder.content.examples.space.desc' => 'Оригинал: "Hello World" → Код: "Hello%20World"',
        'url-encoder-decoder.content.faq_title' => 'Вопросы и ответы',
        'url-encoder-decoder.content.faq.q1' => 'Когда нужно кодировать URL?',
        'url-encoder-decoder.content.faq.a1' => 'При передаче параметров запроса или когда URL содержит пробелы, &, =, ? и другие спецсимволы.',
        'url-encoder-decoder.js.error_process' => '✗ Ошибка обработки URL: ',
        'url-encoder-decoder.js.success_copy' => '✓ Скопировано в буфер обмена',

        'xml-formatter.js.success_copy' => 'Скопировано!',

        'xml-to-csv.editor.btn_clear' => 'Очистить',
        'xml-to-csv.editor.btn_example' => 'Пример',
        'xml-to-csv.editor.ph_input' => '<data><row><name>Ivan</name><age>30</age></row></data>',
        'xml-to-csv.editor.ph_output' => 'Сконвертированный CSV появится здесь...',
        'xml-to-csv.content.what_title' => 'Что такое конвертация XML в CSV?',
        'xml-to-csv.content.what_desc' => 'Конвертация XML в CSV превращает структурированные данные XML в формат значений, разделенных запятыми. CSV универсально поддерживается табличными процессорами, такими как Excel.',
        'xml-to-csv.content.features_title' => 'Особенности',
        'xml-to-csv.content.features.fast.title' => 'Молниеносно',
        'xml-to-csv.content.features.fast.desc' => 'Мгновенная конвертация благодаря оптимизированному парсингу',
        'xml-to-csv.content.features.excel.title' => 'Готово для Excel',
        'xml-to-csv.content.features.excel.desc' => 'Результат идеально открывается в Excel и Google Sheets',
        'xml-to-csv.content.uses_title' => 'Случаи использования',
        'xml-to-csv.content.uses.migration.title' => 'Миграция систем',
        'xml-to-csv.content.uses.migration.desc' => 'Трансформация данных XML из легаси-систем в CSV для импорта.',
        'xml-to-csv.content.how_to_title' => 'Как конвертировать XML в CSV',
        'xml-to-csv.content.how_to.step1.title' => 'Вставьте XML данные',
        'xml-to-csv.content.how_to.step2.title' => 'Нажмите кнопку',
        'xml-to-csv.content.how_to.step3.title' => 'Копируйте и используйте',
        'xml-to-csv.content.example_title' => 'Пример конвертации',
        'xml-to-csv.js.error_no_row' => 'Элементы <row> не найдены в XML',
        'xml-to-csv.js.error_process' => '✗ Ошибка: ',
        'xml-to-csv.js.success_copy' => '✓ Скопировано',

        'xml-to-json.editor.btn_download' => 'Скачать',
        'xml-to-json.editor.btn_example' => 'Пример',
        'xml-to-json.editor.btn_clear' => 'Очистить',
        'xml-to-json.editor.ph_output' => 'Результат JSON появится здесь...',
        'xml-to-json.content.p2' => 'XML был стандартом обмена данными десятилетиями, но современные приложения предпочитают JSON. Наш конвертер помогает бесшовно трансформировать XML в чистый и читаемый JSON.',
        'xml-to-json.content.features_title' => 'Мощные функции',
        'xml-to-json.content.features.attributes.title' => 'Обработка атрибутов',
        'xml-to-json.content.features.attributes.desc' => 'Сохраняет атрибуты XML и корректно переносит их в структуру JSON.',
        'xml-to-json.content.features.nested.title' => 'Вложенные структуры',
        'xml-to-json.content.features.nested.desc' => 'Поддерживает сложные иерархические структуры данных.',
        'xml-to-json.content.features.pretty.title' => 'Красивое форматирование',
        'xml-to-json.content.features.pretty.desc' => 'Чистый, структурированный JSON с отступами.',
        'xml-to-json.content.uses_title' => 'Общие случаи использования',
        'xml-to-json.content.uses.api.title' => 'Интеграция API',
        'xml-to-json.content.uses.api.desc' => 'Конвертация XML-ответов API в JSON для современных JS-приложений.',
        'xml-to-json.content.how_to_title' => 'Как работает конвертация XML в JSON',
        'xml-to-json.js.error_process' => 'Ошибка конвертации XML: ',

        'yaml-to-json-converter.meta.title' => 'Конвертер YAML в JSON',
        'yaml-to-json-converter.meta.description' => 'Мгновенно конвертируйте файлы YAML в JSON. Бесплатно, быстро и безопасно.',
        'yaml-to-json-converter.meta.h1' => 'Конвертер YAML в JSON',
        'yaml-to-json-converter.meta.subtitle' => 'Простая трансформация из YAML в JSON',
        'yaml-to-json-converter.editor.ph_input' => 'name: Ivan\\nage: 30',
        'yaml-to-json-converter.editor.btn_convert' => 'Конвертировать в JSON',
        'yaml-to-json-converter.editor.ph_output' => 'Результат JSON...',
        'yaml-to-json-converter.js.error_convert' => 'Ошибка конвертации YAML: ',
        'yaml-to-json-converter.js.success_copy' => 'JSON скопирован!',
    ],
    'es' => [
        'unicode-encoder-decoder.editor.btn_process_encode' => 'Codificar Unicode',
        'unicode-encoder-decoder.editor.ph_output' => 'Unicode procesado aparecerá aquí...',
        'unicode-encoder-decoder.editor.label_input_decode' => 'Introduce Unicode para decodificar',
        'unicode-encoder-decoder.editor.label_output_decoded' => 'Texto decodificado',
        'unicode-encoder-decoder.editor.btn_process_decode' => 'Decodificar Unicode',
        'unicode-encoder-decoder.content.what_title' => '¿Qué es la codificación Unicode?',
        'unicode-encoder-decoder.content.what_desc' => 'Transforma caracteres en sus puntos de código correspondientes, usualmente como \uXXXX. Esto asegura la representación correcta en entornos ASCII.',
        'unicode-encoder-decoder.content.features_title' => 'Características',
        'unicode-encoder-decoder.content.features.bidirectional.title' => 'Bidireccional',
        'unicode-encoder-decoder.content.features.bidirectional.desc' => 'Codifica a Unicode o decodifica al original',
        'unicode-encoder-decoder.content.features.privacy.title' => 'Privacidad',
        'unicode-encoder-decoder.content.features.privacy.desc' => 'Todo se procesa en tu navegador',
        'unicode-encoder-decoder.content.features.universal.title' => 'Soporte Universal',
        'unicode-encoder-decoder.content.features.universal.desc' => 'Funciona con todos los caracteres Unicode',
        'unicode-encoder-decoder.content.uses_title' => 'Casos de Uso',
        'unicode-encoder-decoder.content.uses.programming.title' => 'Programación',
        'unicode-encoder-decoder.content.uses.programming.desc' => 'Incrusta caracteres especiales en JS o Java con seguridad.',
        'unicode-encoder-decoder.content.uses.data.title' => 'Serialización',
        'unicode-encoder-decoder.content.uses.data.desc' => 'Transmisión segura de no-ASCII en JSON.',
        'unicode-encoder-decoder.content.how_to_title' => 'Cómo Usar',
        'unicode-encoder-decoder.content.how_to.step1.title' => 'Elige Modo',
        'unicode-encoder-decoder.content.how_to.step2.title' => 'Introduce Texto',
        'unicode-encoder-decoder.content.how_to.step3.title' => 'Procesar',
        'unicode-encoder-decoder.content.how_to.step4.title' => 'Copia el Resultado',
        'unicode-encoder-decoder.content.examples_title' => 'Ejemplos Unicode',
        'unicode-encoder-decoder.content.examples.simple.title' => 'Simple/ASCII:',
        'unicode-encoder-decoder.content.examples.simple.desc' => 'Original: "A" → Codificado: "\u0041"',
        'unicode-encoder-decoder.content.faq_title' => 'Preguntas Frecuentes',
        'unicode-encoder-decoder.content.faq.q1' => '¿Por qué usar secuencias de escape?',
        'unicode-encoder-decoder.content.faq.a1' => 'Permiten representar cualquier carácter usando solo ASCII, garantizando compatibilidad total.',
        'unicode-encoder-decoder.js.error_process' => '✗ Error al procesar Unicode: ',
        'unicode-encoder-decoder.js.success_copy' => '✓ Copiado al portapapeles',

        'url-encoder-decoder.editor.btn_process_encode' => 'Codificar URL',
        'url-encoder-decoder.editor.ph_output' => 'URL procesada aparecerá aquí...',
        'url-encoder-decoder.editor.label_input_decode' => 'Introduce URL para decodificar',
        'url-encoder-decoder.editor.label_output_decoded' => 'URL Decodificada',
        'url-encoder-decoder.editor.btn_process_decode' => 'Decodificar URL',
        'url-encoder-decoder.content.p1' => 'Codifica caracteres especiales en tus URLs para una transmisión segura. Procesamiento local en el navegador para máxima privacidad.',
        'url-encoder-decoder.content.features_title' => 'Características',
        'url-encoder-decoder.content.features.bidirectional.title' => 'Bidireccional',
        'url-encoder-decoder.content.how_to_title' => 'Cómo Usar',
        'url-encoder-decoder.content.how_to.step1.title' => 'Modo',
        'url-encoder-decoder.content.how_to.step2.title' => 'Pega URL',
        'url-encoder-decoder.content.how_to.step3.title' => 'Procesar',
        'url-encoder-decoder.content.how_to.step4.title' => 'Copia',
        'url-encoder-decoder.content.examples_title' => 'Ejemplos',
        'url-encoder-decoder.js.error_process' => '✗ Error al procesar URL: ',
        'url-encoder-decoder.js.success_copy' => '✓ Copiado al portapapeles',

        'xml-formatter.js.success_copy' => '¡Copiado!',

        'xml-to-csv.editor.btn_clear' => 'Limpiar',
        'xml-to-csv.editor.btn_example' => 'Ejemplo',
        'xml-to-csv.editor.ph_input' => '<data><row><nombre>Juan</nombre><edad>30</edad></row></data>',
        'xml-to-csv.editor.ph_output' => 'CSV convertido aparecerá aquí...',
        'xml-to-csv.content.what_title' => '¿Qué es XML a CSV?',
        'xml-to-csv.content.what_desc' => 'Transforma datos estructurados XML al formato CSV. Ideal para análisis en Excel y hojas de cálculo.',
        'xml-to-csv.content.features_title' => 'Características',
        'xml-to-csv.content.features.fast.title' => 'Súper Rápido',
        'xml-to-csv.content.features.excel.title' => 'Listo para Excel',
        'xml-to-csv.content.uses_title' => 'Casos de Uso',
        'xml-to-csv.content.how_to_title' => 'Cómo Convertir',
        'xml-to-csv.js.error_no_row' => 'No se hallaron elementos <row> en el XML',
        'xml-to-csv.js.success_copy' => '✓ Copiado',

        'xml-to-json.editor.btn_download' => 'Descargar',
        'xml-to-json.editor.btn_example' => 'Ejemplo',
        'xml-to-json.editor.ph_output' => 'JSON convertido aparecerá aquí...',
        'xml-to-json.content.p2' => 'JSON es el formato preferido en apps modernas. Nuestro convertidor permite pasar de documentos XML a JSON de forma limpia y precisa.',
        'xml-to-json.content.features_title' => 'Funciones Potentes',
        'xml-to-json.content.features.attributes.title' => 'Gestión de Atributos',
        'xml-to-json.content.features.nested.title' => 'Estructuras Anidadas',
        'xml-to-json.content.features.pretty.title' => 'Formato Indentado',
        'xml-to-json.js.error_process' => 'Error al convertir XML: ',

        'yaml-to-json-converter.meta.title' => 'Convertidor YAML a JSON',
        'yaml-to-json-converter.meta.description' => 'Convierte archivos YAML a JSON al instante. Gratis, rápido y seguro.',
        'yaml-to-json-converter.meta.h1' => 'Convertidor YAML a JSON',
        'yaml-to-json-converter.meta.subtitle' => 'Transforma YAML en JSON sin esfuerzo',
        'yaml-to-json-converter.editor.ph_input' => 'nombre: Juan\\nedad: 30',
        'yaml-to-json-converter.editor.btn_convert' => 'Convertir a JSON',
        'yaml-to-json-converter.js.success_copy' => '¡JSON copiado!',
    ]
];

foreach ($locales as $loc) {
    $path = "resources/lang/$loc/tools/$category.json";
    if (!file_exists($path))
        continue;
    $data = json_decode(file_get_contents($path), true);

    foreach ($translations[$loc] as $keyPath => $val) {
        $keys = explode('.', $keyPath);
        $temp = &$data;
        foreach ($keys as $k) {
            if (!isset($temp[$k]))
                $temp[$k] = [];
            $temp = &$temp[$k];
        }
        $temp = $val;
    }

    file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    echo "Updated $loc for $category (Chunk 5)\n";
}
