<?php
$locales = ['ru', 'es'];
$categories = ['converters'];

$translations = [
    'ru' => [
        'rgb-hex-converter' => [
            'meta' => [
                'title' => 'RGB в HEX Конвертер | Конвертация цветов в HEX и RGB',
                'description' => 'Мгновенно преобразуйте значения цвета RGB в шестнадцатеричные (HEX) коды и наоборот. Идеальный инструмент для веб-дизайна и CSS.',
                'h1' => 'RGB ↔ HEX Конвертер',
                'subtitle' => 'Профессиональный инструмент для точного преобразования цветов между форматами RGB и HEX.',
            ],
            'editor' => [
                'to_hex' => 'В HEX',
                'to_rgb' => 'В RGB',
                'label_r' => 'Красный (R)',
                'label_g' => 'Зеленый (G)',
                'label_b' => 'Синий (B)',
                'label_hex' => 'HEX Код',
                'ph_hex' => 'Введите HEX код (например, #FFFFFF)...',
                'btn_convert_hex' => 'Конвертировать в HEX',
                'btn_convert_rgb' => 'Конвертировать в RGB',
                'btn_clear' => 'Очистить всё',
                'btn_copy' => 'Копировать результат',
                'label_result_hex' => 'HEX Результат',
                'label_result_rgb' => 'RGB Результат',
                'error_empty' => 'Пожалуйста, введите значение цвета',
                'error_invalid_rgb' => 'Некорректное значение RGB. Используйте числа от 0 до 255.',
                'success_hex' => '✓ Цвет успешно преобразован в HEX!',
                'error_invalid_hex' => 'Некорректный HEX код. Пример: #FFFFFF или FFFFFF.',
                'success_rgb' => '✓ Цвет успешно преобразован в RGB!',
                'error_general' => 'Произошла ошибка при конвертации.',
                'error_no_copy' => 'Нечего копировать. Сначала выполните конвертацию.',
                'success_copy' => '✓ Скопировано в буфер обмена!',
            ],
            'content' => [
                'p1' => 'Наш конвертер RGB в HEX — это незаменимый онлайн-инструмент для веб-дизайнеров, фронтенд-разработчиков и художников. Он обеспечивает бесшовный перевод между двумя основными цифровыми форматами цветов. Цветовая модель RGB используется экранами для отображения цветов, а HEX-коды являются стандартом в веб-разработке (HTML/CSS).',
                'formats_title' => 'Понимание цветовых форматов',
                'why_title' => 'Зачем конвертировать между RGB и HEX?',
                'how_work_title' => 'Как работает преобразование цветов',
                'faq_title' => 'Часто задаваемые вопросы',
                'formats' => [
                    'rgb' => [
                        'title' => 'Формат RGB (Red, Green, Blue)',
                        'format' => 'Формат',
                        'format_val' => 'rgb(красный, зеленый, синий)',
                        'range' => 'Диапазон',
                        'range_val' => '0-255 для каждого канала',
                        'used_in' => 'Использование',
                        'used_in_val' => 'Цифровые экраны, редакторы изображений',
                    ],
                    'hex' => [
                        'title' => 'Формат HEX (Шестнадцатеричный)',
                        'format' => 'Формат',
                        'format_val' => '#RRGGBB',
                        'range' => 'Диапазон',
                        'range_val' => '00-FF для каждого канала',
                        'used_in' => 'Использование',
                        'used_in_val' => 'HTML, CSS, графический дизайн',
                    ],
                ],
                'why_list' => [
                    'css' => [
                        'title' => 'Веб-разработка',
                        'desc' => 'HEX-коды более компактны и стандартны для использования в CSS-файлах.',
                    ],
                    'design' => [
                        'title' => 'Соответствие дизайна',
                        'desc' => 'Легко переносите цвета из графических редакторов (например, Photoshop) в свой код.',
                    ],
                    'precision' => [
                        'title' => 'Точность цвета',
                        'desc' => 'Гарантирует, что вы используете именно тот оттенок, который задуман.',
                    ],
                ],
                'how_work_t1' => 'Из RGB в HEX',
                'how_work_p1' => 'Каждое значение (0-255) преобразуется в двухсимвольное шестнадцатеричное число. Например, 255 становится FF, а 0 становится 00.',
                'how_work_t2' => 'Из HEX в RGB',
                'how_work_p2' => 'HEX-код разбивается на три пары символов, каждая из которых переводится обратно в десятичное число.',
                'faq' => [
                    'q1' => 'Нужно ли добавлять символ "#" перед HEX-кодом?',
                    'a1' => 'Наш инструмент работает как с символом "#", так и без него. Мы автоматически обработаем ваш ввод.',
                    'q2' => 'Что означает RGB(0,0,0)?',
                    'a2' => 'Это черный цвет. Все три канала (красный, зеленый, синий) выключены или имеют минимальную интенсивность.',
                    'q3' => 'Что означает HEX #FFFFFF?',
                    'a3' => 'Это белый цвет. Все каналы имеют максимальную интенсивность (255 или FF).',
                    'q4' => 'Обеспечивает ли этот инструмент приватность?',
                    'a4' => 'Да, все вычисления выполняются в вашем браузере. Данные о цвете не передаются на сервер.',
                ],
            ],
        ],
        'binary-hex-converter' => [
            'meta' => [
                'title' => 'Двоичный в HEX ↔ HEX в Двоичный Конвертер',
                'description' => 'Быстрый и надежный онлайн-конвертер между двоичной (base-2) и шестнадцатеричной (base-16) системами.',
                'h1' => 'Конвертер Двоичный ↔ HEX',
                'subtitle' => 'Лучший инструмент для прямого преобразования двоичных и шестнадцатеричных чисел.',
            ],
            'editor' => [
                'mode_bin_hex' => 'Из двоичной в HEX',
                'mode_hex_bin' => 'Из HEX в двоичную',
                'label_bin' => 'Двоичный ввод',
                'ph_bin' => 'Введите двоичные цифры (например, 10101011)...',
                'label_out_hex' => 'HEX результат',
                'ph_hex' => 'Результат появится здесь...',
                'label_hex' => 'HEX ввод',
                'ph_in_hex' => 'Введите HEX цифры (например, AB)...',
                'label_out_bin' => 'Двоичный результат',
                'ph_out_bin' => 'Двоичный результат появится здесь...',
                'btn_convert_hex' => 'В шестнадцатеричную',
                'btn_convert_bin' => 'В двоичную',
                'btn_clear' => 'Очистить всё',
                'btn_copy' => 'Копировать результат',
            ],
            'content' => [
                'p1' => 'Наш конвертер двоичных чисел в HEX — это специализированный инструмент для IT-сообщества. Двоичная (base-2) и шестнадцатеричная (base-16) системы являются двумя важнейшими способами представления данных в компьютерах. Так как одна шестнадцатеричная цифра соответствует ровно четырем двоичным битам, этот конвертер обеспечивает прямую связь между этими форматами данных без задержек.',
                'what_title' => 'Зачем переводить двоичный код в HEX?',
                'what_desc' => 'Хотя двоичный код — это язык железа, человеку крайне сложно читать длинные строки из 0 и 1. HEX обеспечивает гораздо более компактное представление. Например, 8-битная строка "10101011" — это просто "AB" в HEX. Это делает HEX стандартом для адресов памяти, цветовых кодов и байтовых данных.',
                'features' => [
                    'instant' => [
                        'title' => 'Реальное время',
                        'desc' => 'Получайте результаты мгновенно без обращения к серверу.',
                    ],
                    'bidirectional' => [
                        'title' => 'Двусторонняя поддержка',
                        'desc' => 'Легко переключайтесь между режимами Bin-to-Hex и Hex-to-Bin.',
                    ],
                    'privacy' => [
                        'title' => '100% Приватность',
                        'desc' => 'Вся обработка происходит на вашем устройстве; данные не покидают браузер.',
                    ],
                    'copy' => [
                        'title' => 'Быстрое копирование',
                        'desc' => 'Экономьте время с помощью встроенной поддержки буфера обмена.',
                    ],
                ],
                'uses' => [
                    'title' => 'Практическое применение',
                    'memory' => [
                        'title' => 'Адресация памяти',
                        'desc' => 'Преобразуйте двоичные значения в HEX-адреса, используемые ОС и отладчиками.',
                    ],
                    'colors' => [
                        'title' => 'Цветопередача',
                        'desc' => 'Поймите, как 8-битные двоичные компоненты формируют HEX-значения в HTML цветах.',
                    ],
                    'encoding' => [
                        'title' => 'Кодирование данных',
                        'desc' => 'Анализируйте байтовые потоки и пакеты данных в сетях и файлах.',
                    ],
                ],
            ],
            'js' => [
                'error_empty' => 'Пожалуйста, введите значение для конвертации',
                'error_invalid_bin' => 'Некорректное двоичное число. Используйте только 0 и 1.',
                'success_hex' => '✓ Успешно переведено в HEX!',
                'error_invalid_hex' => 'Некорректное HEX-число. Используйте 0-9 и A-F.',
                'success_bin' => '✓ Успешно переведено в двоичную систему!',
                'error_general' => 'Ошибка конвертации: ',
                'error_no_output' => 'Нечего копировать! Сначала выполните конвертацию.',
                'success_copy' => '✓ Скопировано в буфер обмена!',
            ],
        ],
        'binary-to-text' => [
            'meta' => [
                'title' => 'Конвертер двоичного кода в текст | Декодировать двоичные данные онлайн',
                'description' => 'Мгновенно преобразуйте двоичный код (0 и 1) в обычный текст. Профессиональный инструмент для декодирования данных в символы ASCII/UTF-8.',
                'h1' => 'Конвертер двоичного кода в текст',
                'subtitle' => 'Лучший инструмент для декодирования двоичных последовательностей в читаемый текст.',
            ],
            'editor' => [
                'btn_convert' => 'Конвертировать в текст',
                'btn_copy' => 'Копировать вывод',
                'btn_download' => 'Скачать текст',
                'btn_example' => 'На примере',
                'btn_clear' => 'Очистить всё',
                'label_input' => 'Двоичный ввод (8-битные блоки)',
                'ph_input' => 'Введите двоичный код (например, 01001000 01100101)...',
                'label_output' => 'Текстовый результат',
                'ph_output' => 'Декодированный текст появится здесь...',
            ],
            'content' => [
                'about_title' => 'Понимание конвертации двоичного кода в текст',
                'about_p1' => 'Двоичный код — это базовый язык компьютеров, представляющий данные как последовательность 0 и 1. Этот инструмент позволяет перевести эти последовательности обратно в буквы с использованием стандартов ASCII/UTF-8.',
                'features_title' => 'Возможности декодирования',
                'features_list' => [
                    '8bit' => 'Поддержка стандартных 8-битных (октет) блоков.',
                    'validation' => 'Проверка корректности ввода двоичных символов (0-1).',
                    'utf8' => 'Полная поддержка ASCII и популярных символов UTF-8.',
                    'instant' => 'Молниеносная обработка на стороне клиента.',
                    'edu' => 'Визуальная обратная связь, идеальная для обучения.',
                    'free' => '100% бесплатно, без ограничений и регистрации.',
                ],
                'uses_title' => 'Профессиональные кейсы',
                'uses_edu_title' => 'Обучение IT',
                'uses_edu_desc' => 'Узнайте, как биты объединяются для формирования символов в таблице ASCII.',
                'uses_prog_title' => 'Отладка ПО',
                'uses_prog_desc' => 'Изучайте потоки данных и дампы памяти, переводя их в читаемый вид.',
                'uses_decoding_title' => 'Восстановление данных',
                'uses_decoding_desc' => 'Восстанавливайте текст из частично переданных пакетов данных.',
                'uses_learning_title' => 'Цифровая грамотность',
                'uses_learning_desc' => 'Поймите связь между компьютерным железом и программами.',
                'how_title' => 'Как декодировать двоичный код',
                'how_desc' => 'Просто вставьте вашу последовательность (группы по 8 бит) в поле ввода. Инструмент автоматически найдет соответствующий символ для каждого байта. Для лучшего результата разделяйте блоки пробелами.',
                'faq_title' => 'FAQ по двоичной конвертации',
                'q1' => 'Нужны ли пробелы между битами?',
                'a1' => 'Да, инструмент лучше всего работает с 8-битными блоками, разделенными пробелами.',
                'q2' => 'Поддерживаются ли неанглийские символы?',
                'a2' => 'Да, поддерживается стандартный ASCII и большинство популярных символов в кодировке UTF-8.',
            ],
            'js' => [
                'error_empty' => 'Пожалуйста, введите двоичный код',
                'error_invalid_chars' => 'Ошибка ввода! Используйте только 0 и 1.',
                'error_invalid_length' => 'Некорректная длина блока! Каждая группа должна содержать 8 бит.',
                'error_general' => 'Произошла ошибка при конвертации: ',
                'error_no_text_copy' => 'Нечего копировать! Сначала выполните конвертацию.',
                'success_copy' => '✓ Успешно скопировано в буфер обмена!',
                'error_no_text_download' => 'Нечего скачивать! Сначала выполните конвертацию.',
            ],
        ],
        'ascii-converter' => [
            'meta' => [
                'title' => 'Бесплатный ASCII Конвертер - Текст в ASCII и наоборот',
                'description' => 'Мгновенно преобразуйте текст в коды ASCII и обратно. Идеально подходит для кодирования, декодирования и представления данных.',
                'h1' => 'Конвертер ASCII',
                'subtitle' => 'Простой перевод между текстовыми символами и их значениями ASCII.',
            ],
            'editor' => [
                'to_ascii' => 'В ASCII',
                'to_text' => 'В текст',
                'label_text' => 'Входной текст',
                'label_ascii' => 'Коды ASCII',
                'ph_text' => 'Введите текст (например, Hello World)...',
                'ph_ascii' => 'Введите коды ASCII (например, 72 101 108 108 111)...',
                'btn_convert_ascii' => 'Перевести в ASCII',
                'btn_convert_text' => 'Перевести в текст',
                'btn_clear' => 'Очистить всё',
                'btn_copy' => 'Копировать результат',
                'label_output_text' => 'Текстовый результат',
                'label_output_ascii' => 'Результат кодов ASCII',
            ],
            'js' => [
                'error_empty' => 'Пожалуйста, введите данные для конвертации',
                'success_ascii' => '✓ Успешно переведено в коды ASCII!',
                'success_text' => '✓ Успешно переведено в текст!',
                'error_invalid_ascii' => 'Обнаружен некорректный код ASCII: ',
                'error_general' => 'Ошибка при конвертации: ',
                'error_no_output' => 'Нечего копировать! Сначала выполните конвертацию.',
                'success_copy' => '✓ Скопировано в буфер обмена!',
            ],
            'content' => [
                'title' => 'ASCII Конвертер: Текст в ASCII и наоборот',
                'subtitle' => 'Универсальный инструмент для перевода символов в коды и обратно.',
                'p1' => 'Наш бесплатный ASCII конвертер — это универсальная онлайн-утилита для разработчиков, студентов и энтузиастов. Она обеспечивает простой способ преобразования обычного текста в соответствующие числовые значения ASCII и наоборот. Будь то отладка кода, изучение представления данных или необходимость кодирования строк, этот инструмент выдает результат мгновенно.',
                'what_title' => 'Что такое ASCII?',
                'what_desc' => 'ASCII (American Standard Code for Information Interchange) — это стандарт кодировки символов. Каждому символу присвоено уникальное числовое значение от 0 до 127. Например, буква "A" — это 65, а пробел — 32.',
                'features' => [
                    'instant' => [
                        'title' => 'Мгновенно',
                        'desc' => 'Результаты в реальном времени при нажатии кнопки.',
                    ],
                    'bidirectional' => [
                        'title' => 'Двусторонний',
                        'desc' => 'Легкое переключение между режимами Текст-в-ASCII и обратно.',
                    ],
                    'privacy' => [
                        'title' => 'Приватность',
                        'desc' => 'Обработка локально в браузере; данные не уходят на сервер.',
                    ],
                ],
                'uses' => [
                    'title' => 'Частое использование',
                    'programming' => [
                        'title' => 'Программирование',
                        'desc' => 'Конвертация для манипуляций со строками и низкоуровневых операций.',
                    ],
                    'learning' => [
                        'title' => 'Обучение',
                        'desc' => 'Отличный ресурс для понимания того, как компьютер видит текст.',
                    ],
                    'encoding' => [
                        'title' => 'Кодирование',
                        'desc' => 'Создание простых закодированных сообщений.',
                    ],
                    'debugging' => [
                        'title' => 'Отладка',
                        'desc' => 'Поиск скрытых или непечатаемых символов.',
                    ],
                ],
                'examples' => [
                    'title' => 'Основные значения ASCII',
                    'a_upper' => 'Заглавная "A"',
                    'a_lower' => 'Строчная "a"',
                    'zero' => 'Цифра "0"',
                    'space' => 'Символ пробела',
                ],
                'faq' => [
                    'title' => 'Частые вопросы',
                    'q1' => 'Этот конвертер бесплатен?',
                    'a1' => 'Да, на 100% бесплатно и без регистрации.',
                    'q2' => 'Поддерживает ли он Юникод?',
                    'a2' => 'Инструмент фокусируется на стандартном наборе ASCII (0-127). Мы работаем над расширением поддержки.',
                    'q3' => 'Безопасно ли это?',
                    'a3' => 'Абсолютно. Данные не покидают ваш компьютер.',
                ],
            ],
        ],
    ],
    'es' => [
        'rgb-hex-converter' => [
            'meta' => [
                'title' => 'Convertidor de RGB a HEX | Conversión de Colores a HEX y RGB',
                'description' => 'Convierta instantáneamente valores de color RGB a códigos hexadecimales (HEX) y viceversa. Herramienta ideal para diseño web y CSS.',
                'h1' => 'Convertidor RGB ↔ HEX',
                'subtitle' => 'Herramienta profesional para la conversión precisa de colores entre los formatos RGB y HEX.',
            ],
            'editor' => [
                'to_hex' => 'A HEX',
                'to_rgb' => 'A RGB',
                'label_r' => 'Rojo (R)',
                'label_g' => 'Verde (G)',
                'label_b' => 'Azul (B)',
                'label_hex' => 'Código HEX',
                'ph_hex' => 'Ingrese el código HEX (ej., #FFFFFF)...',
                'btn_convert_hex' => 'Convertir a HEX',
                'btn_convert_rgb' => 'Convertir a RGB',
                'btn_clear' => 'Borrar Todo',
                'btn_copy' => 'Copiar Resultado',
                'label_result_hex' => 'Resultado HEX',
                'label_result_rgb' => 'Resultado RGB',
                'error_empty' => 'Por favor, ingrese un valor de color',
                'error_invalid_rgb' => 'Valor RGB inválido. Use números entre 0 y 255.',
                'success_hex' => '✓ ¡Color convertido a HEX con éxito!',
                'error_invalid_hex' => 'Código HEX inválido. Ejemplo: #FFFFFF o FFFFFF.',
                'success_rgb' => '✓ ¡Color convertido a RGB con éxito!',
                'error_general' => 'Ocurrió un error durate la conversión.',
                'error_no_copy' => 'Nada que copiar. Realice una conversión primero.',
                'success_copy' => '✓ ¡Copiado al portapapeles!',
            ],
            'content' => [
                'p1' => 'Nuestro convertidor de RGB a HEX es una herramienta en línea indispensable para diseñadores web, desarrolladores frontend y artistas. Proporciona una traducción fluida entre los dos formatos de color digitales principales. El modelo RGB es utilizado por las pantallas, mientras que los códigos HEX son el estándar en el desarrollo web (HTML/CSS).',
                'formats_title' => 'Comprensión de los Formatos de Color',
                'why_title' => '¿Por qué convertir entre RGB y HEX?',
                'how_work_title' => 'Cómo funciona la conversión de colores',
                'faq_title' => 'Preguntas Frecuentes',
                'formats' => [
                    'rgb' => [
                        'title' => 'Formato RGB (Rojo, Verde, Azul)',
                        'format' => 'Formato',
                        'format_val' => 'rgb(rojo, verde, azul)',
                        'range' => 'Rango',
                        'range_val' => '0-255 para cada canal',
                        'used_in' => 'Uso',
                        'used_in_val' => 'Pantallas digitales, editores de imagen',
                    ],
                    'hex' => [
                        'title' => 'Formato HEX (Hexadecimal)',
                        'format' => 'Formato',
                        'format_val' => '#RRGGBB',
                        'range' => 'Rango',
                        'range_val' => '00-FF para cada canal',
                        'used_in' => 'Uso',
                        'used_in_val' => 'HTML, CSS, diseño gráfico',
                    ],
                ],
                'why_list' => [
                    'css' => [
                        'title' => 'Desarrollo Web',
                        'desc' => 'Los códigos HEX son más compactos y estándar para usar en archivos CSS.',
                    ],
                    'design' => [
                        'title' => 'Consistencia de Diseño',
                        'desc' => 'Transfiera fácilmente colores de editores gráficos (como Photoshop) a su código.',
                    ],
                    'precision' => [
                        'title' => 'Precisión de Color',
                        'desc' => 'Garantiza que use exactamente el tono que ha planeado.',
                    ],
                ],
                'how_work_t1' => 'De RGB a HEX',
                'how_work_p1' => 'Cada valor (0-255) se convierte en un número hexadecimal de dos caracteres. Por ejemplo, 255 se convierte en FF y 0 en 00.',
                'how_work_t2' => 'De HEX a RGB',
                'how_work_p2' => 'El código HEX se divide en tres pares de caracteres, cada uno se traduce de nuevo a un número decimal.',
                'faq' => [
                    'q1' => '¿Debo añadir el símbolo "#" antes del código HEX?',
                    'a1' => 'Nuestra herramienta funciona tanto con como sin el símbolo "#". Procesamos automáticamente su entrada.',
                    'q2' => '¿Qué significa RGB(0,0,0)?',
                    'a2' => 'Es el color negro. Los tres canales (rojo, verde, azul) están apagados o tienen la mínima intensidad.',
                    'q3' => '¿Qué significa HEX #FFFFFF?',
                    'a3' => 'Es el color blanco. Todos los canales tienen la máxima intensidad (255 o FF).',
                    'q4' => '¿Esta herramienta garantiza mi privacidad?',
                    'a4' => 'Sí, todos los cálculos se realizan en su navegador. Los datos del color no se envían al servidor.',
                ],
            ],
        ],
        'binary-hex-converter' => [
            'meta' => [
                'title' => 'Convertidor de Binario a HEX ↔ HEX a Binario',
                'description' => 'Convertidor en línea rápido y confiable entre los sistemas binario (base-2) y hexadecimal (base-16).',
                'h1' => 'Convertidor Binario ↔ HEX',
                'subtitle' => 'La herramienta definitiva para la transformación numérica directa entre binario y hexadecimal.',
            ],
            'editor' => [
                'mode_bin_hex' => 'De Binario a Hexadecimal',
                'mode_hex_bin' => 'De Hexadecimal a Binario',
                'label_bin' => 'Entrada Binaria',
                'ph_bin' => 'Ingrese dígitos binarios (ej., 10101011)...',
                'label_out_hex' => 'Salida Hexadecimal',
                'ph_hex' => 'El resultado aparecerá aquí...',
                'label_hex' => 'Entrada Hexadecimal',
                'ph_in_hex' => 'Ingrese dígitos hex (ej., AB)...',
                'label_out_bin' => 'Salida Binaria',
                'ph_out_bin' => 'El resultado aparecerá aquí...',
                'btn_convert_hex' => 'Convertir a Hex',
                'btn_convert_bin' => 'Convertir a Binario',
                'btn_clear' => 'Borrar Todo',
                'btn_copy' => 'Copiar Resultado',
            ],
            'content' => [
                'p1' => 'Nuestro convertidor de binario a hexadecimal es una herramienta especializada para la comunidad informática. El binario (base-2) y el hexadecimal (base-16) son los dos sistemas numéricos más importantes en informática. Dado que un dígito hex corresponde exactamente a cuatro bits binarios, este convertidor proporciona un puente directo.',
                'what_title' => '¿Por qué convertir de binario a HEX?',
                'what_desc' => 'Aunque el binario es el lenguaje del hardware, es difícil de leer para los humanos. El hexadecimal proporciona una representación mucho más compacta. Por ejemplo, "10101011" es simplemente "AB" en hex. Esto hace que el hex sea el estándar para direcciones de memoria y códigos de color.',
                'features' => [
                    'instant' => [
                        'title' => 'Conversión en Tiempo Real',
                        'desc' => 'Obtenga resultados al instante sin retrasos del lado del servidor.',
                    ],
                    'bidirectional' => [
                        'title' => 'Soporte Bidireccional',
                        'desc' => 'Cambie fácilmente entre los modos Bin-a-Hex y Hex-a-Bin.',
                    ],
                    'privacy' => [
                        'title' => 'Privacidad Total',
                        'desc' => 'Todo el procesamiento es local; sus datos nunca salen de su dispositivo.',
                    ],
                    'copy' => [
                        'title' => 'Copia Instantánea',
                        'desc' => 'Ahorre tiempo con el soporte para portapapeles integrado.',
                    ],
                ],
                'uses' => [
                    'title' => 'Aplicaciones Prácticas',
                    'memory' => [
                        'title' => 'Direccionamiento de Memoria',
                        'desc' => 'Convierta valores binarios a las direcciones hex usadas por SO y depuradores.',
                    ],
                    'colors' => [
                        'title' => 'Representación de Color',
                        'desc' => 'Comprenda cómo los componentes binarios forman los valores hex en colores HTML.',
                    ],
                    'encoding' => [
                        'title' => 'Codificación de Datos',
                        'desc' => 'Analice flujos de bytes y paquetes de datos en redes y archivos.',
                    ],
                ],
            ],
            'js' => [
                'error_empty' => 'Por favor, ingrese un valor para convertir',
                'error_invalid_bin' => 'Número binario inválido. Use solo 0 y 1.',
                'success_hex' => '✓ ¡Convertido a hexadecimal con éxito!',
                'error_invalid_hex' => 'Número hexadecimal inválido. Use 0-9 y A-F.',
                'success_bin' => '✓ ¡Convertido a binario con éxito!',
                'error_general' => 'Error de conversión: ',
                'error_no_output' => '¡Nada que copiar! Realice una conversión primero.',
                'success_copy' => '✓ ¡Copiado al portapapeles!',
            ],
        ],
        'binary-to-text' => [
            'meta' => [
                'title' => 'Convertidor de Binario a Texto | Decodificar Código Binario',
                'description' => 'Convierta código binario (0 y 1) a texto plano al instante. Herramienta profesional para decodificar datos binarios en caracteres ASCII/UTF-8.',
                'h1' => 'Convertidor de Binario a Texto',
                'subtitle' => 'La herramienta definitiva para decodificar secuencias binarias en texto legible.',
            ],
            'editor' => [
                'btn_convert' => 'Convertir a Texto',
                'btn_copy' => 'Copiar Salida',
                'btn_download' => 'Descargar Texto',
                'btn_example' => 'Cargar Ejemplo',
                'btn_clear' => 'Borrar Todo',
                'label_input' => 'Entrada Binaria (bloques de 8 bits)',
                'ph_input' => 'Ingrese código binario aquí (ej., 01001000 01100101)...',
                'label_output' => 'Salida de Texto',
                'ph_output' => 'El texto decodificado aparecerá aquí...',
            ],
            'content' => [
                'about_title' => 'Comprensión de la conversión de Binario a Texto',
                'about_p1' => 'El binario es el lenguaje fundamental de las computadoras. Esta herramienta le permite traducir estas secuencias de nuevo a texto humano usando codificación ASCII/UTF-8.',
                'features_title' => 'Características de Decodificación',
                'features_list' => [
                    '8bit' => 'Soporta bloques binarios estándar de 8 bits (octetos).',
                    'validation' => 'Validación en tiempo real de caracteres binarios.',
                    'utf8' => 'Soporte completo para caracteres ASCII y UTF-8 comunes.',
                    'instant' => 'Procesamiento rápido del lado del cliente.',
                    'edu' => 'Retroalimentación visual ideal para propósitos educativos.',
                    'free' => '100% gratis sin límites ni registro.',
                ],
                'uses_title' => 'Casos de Uso Profesionales',
                'uses_edu_title' => 'Educación Informática',
                'uses_edu_desc' => 'Aprenda cómo los bits se agrupan para formar caracteres en la tabla ASCII.',
                'uses_prog_title' => 'Depuración de Software',
                'uses_prog_desc' => 'Inspeccione flujos de datos y volcados de memoria al convertirlos en texto.',
                'uses_decoding_title' => 'Reconstrucción de Datos',
                'uses_decoding_desc' => 'Recupere texto de paquetes de datos binarios transmitidos parcialmente.',
                'uses_learning_title' => 'Alfabetización Digital',
                'uses_learning_desc' => 'Comprenda el puente entre el hardware y las aplicaciones.',
                'how_title' => 'Cómo Decodificar Código Binario',
                'how_desc' => 'Simplemente pegue su secuencia binaria (grupos de 8 bits) en el campo de entrada. La herramienta encontrará automáticamente el carácter correspondiente. Separe los bloques con espacios.',
                'faq_title' => 'FAQ de Conversión Binaria',
                'q1' => '¿Debo usar espacios entre mis bits binarios?',
                'a1' => 'Sí, la herramienta funciona mejor con bloques de 8 bits separados por espacios.',
                'q2' => '¿Soporta caracteres que no sean ingleses?',
                'a2' => 'Sí, soporta caracteres estándar ASCII y la mayoría de los codificados en UTF-8.',
            ],
            'js' => [
                'error_empty' => 'Por favor, ingrese código binario',
                'error_invalid_chars' => '¡Entrada inválida! Use solo 0 y 1.',
                'error_invalid_length' => '¡Longitud de bloque inválida! Cada grupo debe tener 8 bits.',
                'error_general' => 'Ocurrió un error: ',
                'error_no_text_copy' => '¡Nada que copiar! Realice una conversión primero.',
                'success_copy' => '✓ ¡Copiado al portapapeles!',
                'error_no_text_download' => '¡Nada que descargar! Realice una conversión primero.',
            ],
        ],
        'ascii-converter' => [
            'meta' => [
                'title' => 'Convertidor ASCII Gratis - Texto a ASCII y viceversa',
                'description' => 'Convierta texto a códigos ASCII y viceversa al instante. Gratis y profesional.',
                'h1' => 'Convertidor ASCII',
                'subtitle' => 'Traducción sencilla entre caracteres de texto y valores ASCII.',
            ],
            'editor' => [
                'to_ascii' => 'A ASCII',
                'to_text' => 'A Texto',
                'label_text' => 'Texto de Entrada',
                'label_ascii' => 'Códigos ASCII',
                'ph_text' => 'Ingrese texto (ej., Hello World)...',
                'ph_ascii' => 'Ingrese códigos ASCII (ej., 72 101 108 108 111)...',
                'btn_convert_ascii' => 'Convertir a ASCII',
                'btn_convert_text' => 'Convertir a Texto',
                'btn_clear' => 'Borrar Todo',
                'btn_copy' => 'Copiar Resultado',
                'label_output_text' => 'Resultado de Texto',
                'label_output_ascii' => 'Resultado de Códigos ASCII',
            ],
            'js' => [
                'error_empty' => 'Por favor, ingrese datos para convertir',
                'success_ascii' => '✓ ¡Convertido a códigos ASCII con éxito!',
                'success_text' => '✓ ¡Convertido a texto con éxito!',
                'error_invalid_ascii' => 'Código ASCII inválido detectado: ',
                'error_general' => 'Error durante la conversión: ',
                'error_no_output' => '¡Nada que copiar! Realice una conversión primero.',
                'success_copy' => '✓ ¡Copiado al portapapeles!',
            ],
            'content' => [
                'title' => 'Convertidor ASCII: Texto a ASCII y viceversa',
                'subtitle' => 'La herramienta definitiva para la traducción de caracteres a códigos.',
                'p1' => 'Nuestro convertidor ASCII gratuito es una utilidad en línea versátil para desarrolladores y estudiantes. Proporciona una forma sencilla de transformar texto plano en valores numéricos ASCII.',
                'what_title' => '¿Qué es ASCII?',
                'what_desc' => 'ASCII es un estándar de codificación de caracteres. Cada carácter tiene asignado un valor numérico único de 0 a 127.',
                'features' => [
                    'instant' => [
                        'title' => 'Conversión Instantánea',
                        'desc' => 'Resultados en tiempo real al hacer clic.',
                    ],
                    'bidirectional' => [
                        'title' => 'Soporte Bidireccional',
                        'desc' => 'Cambie fácilmente entre modos.',
                    ],
                    'privacy' => [
                        'title' => 'Privacidad Garantizada',
                        'desc' => 'Todo el procesamiento ocurre localmente.',
                    ],
                ],
                'uses' => [
                    'title' => 'Usos Comunes',
                    'programming' => [
                        'title' => 'Programación',
                        'desc' => 'Manipulación de cadenas y operaciones de bajo nivel.',
                    ],
                    'learning' => [
                        'title' => 'Educativo',
                        'desc' => 'Comprender cómo las computadoras representan el texto.',
                    ],
                ],
                'examples' => [
                    'title' => 'Valores ASCII Comunes',
                    'a_upper' => 'Mayúscula "A"',
                    'a_lower' => 'Minúscula "a"',
                    'zero' => 'Número "0"',
                    'space' => 'Espacio',
                ],
                'faq' => [
                    'title' => 'Preguntas Frecuentes',
                    'q1' => '¿Es gratis?',
                    'a1' => 'Sí, 100% gratis y sin registro.',
                    'q2' => '¿Es seguro?',
                    'a2' => 'Absolutamente, sus datos no salen de su equipo.',
                ],
            ],
        ],
    ],
];

foreach ($locales as $locale) {
    if (!isset($translations[$locale]))
        continue;
    foreach ($categories as $cat) {
        $jsonPath = "resources/lang/$locale/tools/$cat.json";
        if (file_exists($jsonPath)) {
            $data = json_decode(file_get_contents($jsonPath), true) ?: [];
            foreach ($translations[$locale] as $slug => $content) {
                $data[$slug] = $content;
            }
            file_put_contents($jsonPath, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
            echo "Updated $jsonPath\n";
        }
    }
}
echo "Batch 1.2 update completed.\n";
